import { one, paragraph, segment, type Chapter } from "../../schema";

export const chaptersEarly: Chapter[] = [
  {
    id: "cap-1",
    number: 1,
    title: "Caput I",
    heading: "Christum esse viam humilitatis, quo pervenitur ad veritatem",
    paragraphs: [
      paragraph("p1", "1", [
        segment(
          "p1.1",
          "Locuturus ergo de gradibus humilitatis, quos beatus Benedictus non numerandos, sed ascendendos proponit (Reg. cap. 7), prius ostendo, si possum, quo per illos perveniendum sit, ut audito fructu perventionis, minus gravet labor ascensionis.",
          "I propose to speak of the degrees of humility, as St. Benedict sets them before us, as not only to be enumerated but to be attained. And I will first indicate, to the best of my ability, the goal that may be reached by their means, so that when you have heard the result of its attainment, the toil involved in the ascent may be less severely felt.",
          "About to speak, then, of the degrees of humility, which blessed Benedict proposes not to be numbered but to be ascended, I first show, if I can, whither one must arrive through them, so that, the fruit of arrival having been heard, the labour of ascent may weigh less.",
        ),
        segment(
          "p1.2",
          "Proponit itaque Dominus nobis viae laborem, laboris mercedem. Ego sum, inquit, via, veritas, et vita (Ioan. xiv, 6). Viam dicit humilitatem, quae ducit ad veritatem. Altera labor, altera fructus laboris est.",
          "So let our Lord set before us the difficulties that we shall encounter, and the reward that we shall receive for our toilsome journey. I am, saith He, The Way and the Truth and the Life. He calls humility ‘the way’ because it leads to the truth. In the former lies the labour, in the latter is the reward.",
          "The Lord therefore sets before us the labour of the way, the wage of the labour. ‘I am,’ he says, ‘the way, the truth, and the life.’ He calls the way humility, which leads to the truth. The one is labour, the other the fruit of labour.",
        ),
        segment(
          "p1.3",
          "Vnde sciam, inquis, quod ibi de humilitate locutus sit, cum indeterminate dixerit: Ego sum via? Audi apertius: Discite a me quia mitis sum et humilis corde (Matth. xi, 29). Se ergo proponit humilitatis exemplum, mansuetudinis formam. Si imitaris eum, non ambulas in tenebris, sed habebis lumen vitae (Ioan. viii, 12).",
          "But, you may ask, how am I to know that He was here speaking of humility, since He says without further explanation, I am the Way? Listen to His more explicit statement, Learn of me because I am meek and humble of heart. In this He exhibits Himself as a type of humility, a model of meekness. If you imitate Him, you are not walking in darkness, but you will have the light of life.",
          "‘Whence shall I know,’ you say, ‘that he spoke there of humility, when he said indeterminately: I am the way?’ Hear more openly: ‘Learn from me, because I am meek and humble of heart.’ He therefore proposes himself as the example of humility, the form of gentleness. If you imitate him, you do not walk in darkness, but you will have the light of life.",
        ),
        segment(
          "p1.4",
          "Quid est lumen vitae, nisi veritas, quae illuminans omnem hominem venientem in hunc mundum, ostendit ubi sit vera vita? Ideo cum dixisset: Ego sum via et veritas, subdidit, et vita: ac si diceret: Ego sum via, quae ad veritatem duco; ego sum veritas, quae vitam promitto; ego sum vita, quam do.",
          "What is the light of life, unless it be the truth, which lightens every man that comes into the world, and shows us wherein true life consists? For this reason, to those words of His I am the Way and the Truth, He added and the Life, as though He meant to say, I am the way because I lead to the truth, I am the truth because I promise life, I am myself the life which I give.",
          "What is the light of life, if not the truth, which, illuminating every man coming into this world, shows where the true life is? Therefore when he had said: I am the way and the truth, he added, and the life: as if he were saying: I am the way, who lead to the truth; I am the truth, who promise life; I am the life, which I give.",
        ),
        segment(
          "p1.5",
          "Haec est enim, ait, vita aeterna, ut cognoscant te verum Deum, et quem misisti Iesum Christum (Ioan. xvii, 3). Vel sic, quasi tu dicas: Viam considero, id est humilitatem: fructum desidero, veritatem. Sed quid si tantus est labor viae, ut ad optatum fructum non possim pervenire? Respondet: Ego sum vita, id est viaticum, quo sustenteris in via.",
          "For this, saith He, is life eternal, that they may know thee the true God, and Jesus Christ whom thou hast sent. But admitting this, you may still say, I recognize humility as the way; I long for truth as the reward; but what if the toil of the journey be so great that I am unable to reach the desired goal? To this He replies, I am the life, that is the provision for the journey by which you will be supported on the way.",
          "For this, he says, is eternal life, that they may know you the true God, and Jesus Christ whom you have sent. Or thus, as if you should say: I consider the way, that is humility; I desire the fruit, the truth. But what if the labour of the way is so great that I cannot arrive at the hoped-for fruit? He answers: I am the life, that is the viaticum by which you may be sustained on the way.",
        ),
        segment(
          "p1.6",
          "Clamat igitur errantibus, et viam ignorantibus: Ego sum via; dubitantibus, et non credentibus: Ego sum veritas; iam ascendentibus, sed lassescentibus: Ego sum vita. Satis, ut reor, ostensum est ex proposito capitulo Evangelii, cognitionem veritatis fructum esse humilitatis.",
          "So He exclaims to the wanderers and to those who do not know the road, I am the way, to the doubters and disbelievers, I am the truth, to those who have begun the ascent and are getting tired, I am the life. I think that it has been made sufficiently clear by the passage quoted from the Gospel that the reward of humility is the apprehension of the truth.",
          "He therefore cries to those wandering and ignorant of the way: I am the way; to those doubting and not believing: I am the truth; to those already ascending but growing weary: I am the life. Enough, as I think, has been shown from the proposed chapter of the Gospel, that the knowledge of the truth is the fruit of humility.",
          [
            {
              kind: "syntax",
              title: "cognitionem veritatis fructum esse humilitatis",
              body: "Mills turns the infinitive clause into ‘the reward of humility is the apprehension of the truth.’ Bernard’s order is: knowledge of truth is humility’s fruit. The close line keeps that predicate.",
            },
          ],
        ),
        segment(
          "p1.7",
          "Accipe et aliud. Confiteor tibi, Pater, Domine caeli et terrae, quia abscondisti haec, haud dubium quin veritatis secreta, a sapientibus et prudentibus, id est a superbis, et revelasti ea parvulis (Luc. x, 21), hoc est humilibus. Et in hoc apparet quod veritas, quae superbis absconditur, humilibus revelatur.",
          "And take another passage, I praise thee, Father of heaven and earth, because thou hast hidden these things (that undoubtedly means ‘secret truths’) from the wise and prudent (that is from the proud) and hast revealed them unto babes (that is to the humble). This affords further evidence that the truth which is withheld from the proud, is disclosed to the humble.",
          "Receive also another. I confess to you, Father, Lord of heaven and earth, because you have hidden these things — no doubt the secrets of truth — from the wise and prudent, that is from the proud, and have revealed them to little ones, that is to the humble. And in this it appears that the truth, which is hidden from the proud, is revealed to the humble.",
        ),
      ]),
    ],
  },
  {
    id: "cap-2",
    number: 2,
    title: "Caput II",
    heading: "The definition of humility",
    paragraphs: [
      paragraph("p2", "2", [
        segment(
          "p2.1",
          "Humilitatis vero talis potest esse definitio: humilitas est virtus, qua homo verissima sui cognitione sibi ipse vilescit.",
          "And the following may be taken as the definition of humility. It is the virtue which enables a man to see himself in his true colours and thereby to discover his worthlessness.",
          "But of humility there can be a definition of this kind: humility is the virtue by which a man, by a most-true knowledge of himself, becomes cheap to himself.",
          [
            {
              kind: "syntax",
              title: "verissima sui cognitione / sibi ipse vilescit",
              body: "The ablative is instrumental: by a most-true self-knowledge. Vilescit is reflexive and inchoative — he becomes cheap to himself. Mills makes a moral discovery (‘true colours… worthlessness’). Bernard states a cognitive event.",
            },
          ],
        ),
        segment(
          "p2.2",
          "Haec autem convenit his, qui ascensionibus in corde suo dispositis, de virtute in virtutem, id est de gradu in gradum proficiunt, donec ad culmen humilitatis perveniant, in quo velut in Sion, id est in speculatione, positi, veritatem prospiciant.",
          "And this is the characteristic virtue of those who are disposed in their hearts to ascend by steps from virtue to virtue, until they reach the summit of humility; where, standing on Sion as on a watch-tower, they may survey the truth.",
          "And this befits those who, having set ascents in their heart, advance from virtue to virtue, that is from degree to degree, until they arrive at the summit of humility, in which, placed as if on Sion, that is in speculation, they look out upon the truth.",
        ),
        segment(
          "p2.3",
          "Etenim, inquit, benedictionem dabit legislator, quia qui dedit legem, dabit et benedictionem, hoc est qui iussit humilitatem, perducet ad veritatem. Quis vero est hic legislator, nisi dulcis et rectus Dominus, qui legem dedit delinquentibus in via?",
          "For, saith the Psalmist, the law-giver shall give a blessing. He then who gave the law will also provide the blessing — that is to say, he who has prescribed humility will conduct us to the truth. And who is this lawgiver but the kind and righteous Lord who has given a law to those who fail in the way?",
          "For, he says, the lawgiver will give a blessing, because he who gave the law will also give the blessing, that is, he who commanded humility will lead through to the truth. But who is this lawgiver, if not the sweet and upright Lord, who gave a law to those failing on the way?",
        ),
        segment(
          "p2.4",
          "In via quippe delinquunt, qui veritatem derelinquunt. Sed numquid vel sic a dulci Domino derelinquuntur? Ipsis ergo dulcis et rectus Dominus legem dat viam humilitatis, per quam redeant ad cognitionem veritatis. Dat occasionem recuperandae salutis, quia dulcis est; non tamen absque disciplina legis, quia rectus est. Dulcis, quia perire non patitur; rectus, qui punire non obliviscitur.",
          "And surely those who have forsaken the truth have failed on the way. But are they on that account forsaken by the kind Lord? Nay, but it is for these very persons that the kind and righteous Lord prescribes the path of humility, by their return to which they may discover the truth. He allows them an opportunity of regaining salvation because He is kind, yet not without the discipline of law because He is righteous. In His kindness He will not permit their ruin, in His righteousness He cannot omit their punishment.",
          "For they fail on the way who abandon the truth. But are they even so abandoned by the sweet Lord? To these very ones, then, the sweet and upright Lord gives as law the way of humility, through which they may return to the knowledge of the truth. He gives the occasion of recovering salvation, because he is sweet; yet not without the discipline of the law, because he is upright. Sweet, because he does not suffer them to perish; upright, who does not forget to punish.",
        ),
      ]),
    ],
  },
  {
    id: "cap-3",
    number: 3,
    title: "Caput III",
    heading: "Quo fructu ascendantur gradus humilitatis",
    paragraphs: [
      one(
        "p3",
        "3",
        "Hanc itaque legem, qua reditur ad veritatem, beatus Benedictus per duodecim gradus disponit: ut sicut per decem praecepta legis ac geminam circumcisionem (in quo duodenarius numerus adimpletur) ad Christum venitur; ita his duodecim gradibus ascensis, veritas apprehendatur. Illud quoque quod in scala illa, quae in typo humilitatis Iacob monstrata est, Dominus desuper innixus apparuit (Gen. xxviii, 12, 13), quid nobis aliud innuit, nisi quod in culmine humilitatis constituitur cognitio veritatis? Dominus quippe de summitate scalae prospiciebat super filios hominum tanquam Veritas, cuius oculi sicut fallere nolunt, ita falli non norunt, ut videret si sit intelligens aut requirens Deum. An non tibi de alto videtur clamare ac dicere requirentibus se (novit enim qui sunt eius): Transite ad me, omnes qui concupiscitis me, et a generationibus meis implemini? (Eccli. xxiv, 26) et illud: Venite ad me, omnes qui laboratis et onerati estis, et ego vos reficiam (Matth. xi, 28). Venite, inquit. Quo? Ad me veritatem. Qua? Per humilitatem. Quo fructu? Ego vos reficiam. Sed quae est refectio quam Veritas ascendentibus promittit, pervenientibus reddit? An forte ipsa est charitas? Ad hanc quippe, ut ait beatus Benedictus, ascensis omnibus humilitatis gradibus monachus mox perveniet. Vere dulcis et suavis cibus charitas, quae fessos allevat, debiles roborat, maestos laetificat, iugum denique Veritatis facit suave et onus leve.",
        "St. Benedict enumerates twelve degrees in this law by which the return to truth is made; so that as access to Christ is gained when the Ten Commandments and the two-fold circumcision — which together make up the number of twelve — have been passed, truth may likewise be attained by passing through these twelve degrees. And what can be the significance of the fact that the Lord appeared leaning over that ladder which was shown to Jacob as a symbol of humility, but that the recognition of truth begins when the height of humility is reached? For then the Lord, whose eyes, as He is the embodiment of truth, could neither deceive nor be deceived, was looking down from the top of that ladder over the sons of men to discover whether there is anyone who understands or seeks after God. And does He not seem to you to cry aloud from on high and to say to those who seek Him (for He knows who are His), Come over to me ye who desire me, and be filled with fruits, and also, Come unto me ye who labour and are burdened and I will refresh you? Come, He says. Where? To me — Who am the truth. How? By humility. What is the fruit? I will refresh you. But what refreshment is this that Truth promises to those who attempt and gives to those who attain? Is it perchance love? Then this it is at which, as St. Benedict says, the monk who has passed through all the degrees of humility will ere long arrive. Truly love is delightful and pleasant food, supplying rest to the weary, strength to the weak, and joy to the sorrowful. It in fact renders the yoke of truth easy and its burden light.",
        "This law, then, by which one returns to the truth, blessed Benedict arranges through twelve degrees: so that as through the ten precepts of the law and the twin circumcision (in which the number twelve is fulfilled) one comes to Christ, so, these twelve degrees having been ascended, the truth may be grasped. That also, that on that ladder which was shown to Jacob in the type of humility the Lord appeared leaning from above — what else does it hint to us, if not that at the summit of humility the knowledge of truth is established? For the Lord was looking out from the height of the ladder over the sons of men as Truth, whose eyes as they do not wish to deceive, so they do not know how to be deceived, that he might see whether there is one understanding or seeking God. Does he not seem to you to cry from on high and to say to those seeking him (for he knows who are his): Pass over to me, all who desire me, and be filled from my generations? and that: Come to me, all who labour and are burdened, and I will refresh you. Come, he says. Whither? To me, the truth. By what? Through humility. With what fruit? I will refresh you. But what is the refreshment which Truth promises to those ascending, and pays to those arriving? Is it perhaps charity itself? For to this, as blessed Benedict says, the monk, all the degrees of humility having been ascended, will soon arrive. Truly sweet and pleasant food is charity, which lifts the weary, strengthens the weak, gladdens the sad, and finally makes the yoke of Truth sweet and the burden light.",
        [
          {
            kind: "word",
            title: "charitas as the refectio",
            body: "Bernard names the refreshment charitas. Mills says ‘love’. Keep charity in the close line so the later ferculum Salomonis and the three foods stay one vocabulary.",
          },
        ],
      ),
      one(
        "p4",
        "4",
        "Bonus cibus charitas, quae media in ferculo Salomonis consistens, diversarum odore virtutum, velut diversi generis fragrantia pigmentorum, esurientes reficit, iucundat reficientes. Ibi siquidem apponitur pax, patientia, benignitas, longanimitas, gaudium in Spiritu Sancto; et si quae sint aliae veritatis seu sapientiae generationes, apparantur in illa. Habet et humilitas in eodem ferculo suas epulas, panem scilicet doloris et vinum compunctionis, quas primo Veritas incipientibus offert, quibus utique dicitur: Surgite postquam sederitis, qui manducatis panem doloris. Habet ibidem contemplatio ex adipe frumenti solidum cibum sapientiae, cum vino quod laetificat cor hominis, ad quem Veritas perfectos invitat, dicens: Comedite, amici mei, et bibite, et inebriamini, carissimi. Media, inquit, charitate constravit propter filias Ierusalem, propter imperfectas videlicet animas, quae dum adhuc solidum illum cibum minus capere possunt, interim charitatis lacte, oleo pro vino nutriendae sunt. Quae recte media describitur, quia eius suavitas nec incipientibus praesto est, prohibente timore, nec perfectis satis est, pro abundantiori contemplationis dulcedine.",
        "Love is good food, which, as the central dish on Solomon’s dinner table, by the aroma of various virtues as by the fragrance of different condiments, refreshes those who are hungry and delights those who give the refreshment. For on it are set out peace, patience, kindness, forbearance, joy in the Holy Ghost; and if there are any other products of truth or of wisdom, they too are there. Humility also has her dishes on the same tray, namely, the bread of affliction and the wine of remorse. These are the things which Truth offers in the first place to beginners, for to them it is said, Rise after ye have sat down, ye who eat the bread of sorrow. There also contemplation has its solid food, made of the fat essence of the corn, and the wine that maketh glad the heart of man. To this food Truth invites those who have accomplished their course, saying: Eat, my friends, and drink and be inebriated, my dearly-beloved. The midst, saith he, he covered with love, for the daughters of Jerusalem — that is to say, for the sake of the immature souls which, while they are as yet unable to receive solid food, must meanwhile be fed with the milk of love instead of with bread, and with oil instead of with wine. And love is rightly called the central course, because beginners are unable, through their timidity, to take advantage of its sweetness, while to those who have arrived at maturity it is an insufficient substitute for the deeper delight of full vision.",
        "Good food is charity, which, standing in the middle on Solomon’s tray, by the scent of diverse virtues, as by the fragrance of spices of diverse kind, refreshes the hungry and gladdens those who refresh. For there is set out peace, patience, kindness, long-suffering, joy in the Holy Spirit; and if there are any other generations of truth or of wisdom, they are prepared in it. Humility also has on the same tray her banquets, namely the bread of sorrow and the wine of compunction, which Truth first offers to beginners, to whom indeed it is said: Rise after you have sat, you who eat the bread of sorrow. Contemplation has there likewise, from the fat of wheat, the solid food of wisdom, with the wine that gladdens the heart of man, to which Truth invites the perfect, saying: Eat, my friends, and drink, and be inebriated, most dear ones. The middle, he says, he paved with charity for the daughters of Jerusalem, namely for imperfect souls, who, while they can still less take that solid food, must meanwhile be nourished with the milk of charity, with oil for wine. Which is rightly described as middle, because its sweetness is not at hand for beginners, fear forbidding, nor is it enough for the perfect, because of the more abundant sweetness of contemplation.",
      ),
      one(
        "p5",
        "5",
        "Primus ergo cibus est humilitatis, purgatorius cum amaritudine; secundus charitatis, consolatorius cum dulcedine; tertius contemplationis, solidus cum fortitudine. Dixi, ut potui, quo fructu humilitatis gradus ascendi debeant; dicam, ut potero, quo ordine ad propositum bravium veritatis perducant. Sed quia ipsa quoque veritatis agnitio in tribus gradibus consistit, ipsos breviter, si possum, distinguo, quatenus ex hoc clarius innotescat, ad quem trium veritatis, duodecimus humilitatis pertingat. Inquirimus namque veritatem in nobis, in proximis, in sui natura. In nobis, nosmetipsos diiudicando; in proximis, eorum malis compatiendo; in sui natura, mundo corde contemplando. Observa sicut numerum, ita et ordinem. Primo te doceat Veritas ipsa, quare prius in proximis quam in sui debeat inquiri natura. Post haec accipies, cur prius in te quam in proximis inquirere debeas. In numero siquidem beatitudinum, quas suo sermone distinxit, prius misericordes quam mundicordes posuit. Misericordes quippe cito in proximis veritatem deprehendunt, dum suos affectus in illos extendunt, dum sic per charitatem se illis conformant, ut illorum vel bona, vel mala, tanquam propria sentiant. Cum infirmis infirmantur, cum scandalizatis uruntur (II Cor. xi, 29). Gaudere cum gaudentibus, flere cum flentibus consueverunt (Rom. xii, 15). Hac charitate fraterna cordis acie mundata, veritatem delectantur in sui contemplari natura, pro cuius amore mala tolerant aliena. Qui vero se ita fratribus non consociant, sed e contrario aut flentibus insultant, aut gaudentibus derogant, dum quod in illis est, in se non sentiunt, quia similiter affecti non sunt, veritatem in proximis qualiter deprehendere possunt?",
        "So the first course is humility, purifying by its bitterness, the second is love, comforting by its sweetness, the third is full vision, secure in its strength. I have stated, as well as I can do so, the blessings to be gained by passing upwards through the degrees of humility. I will now, to the best of my ability, explain the process by which these lead to the promised prize — the attainment of truth. But as the recognition of truth is gradual, I will, if I can do so, indicate its three degrees, in order to make it more clear to which of these the twelfth degree of humility leads. We seek for truth in ourselves; in our neighbours, and in its essential nature. We find it first in ourselves by severe self scrutiny, then in our neighbours by compassionate indulgence, and, finally, in its essential nature by that direct vision which belongs to the pure in heart. Observe both the number and the sequence. To begin with, let Him who is the Truth teach you that you must search for truth in those around you before you look for it in its intrinsic purity. You will afterwards learn why you must search for it in yourself before you do so in your neighbours. Thus in the enumeration of the Beatitudes He placed ‘the merciful’ before ‘the pure in heart’. For the merciful quickly discover truth in their neighbours when they extend their sympathy to them, and so kindly identify themselves with them that they feel their good and evil characteristics as if they were their own. They are weak with those that are weak, with those who are offended they burn. They have made it their habit to rejoice with them that rejoice and weep with them that weep. When their spiritual vision has been made clear by this brotherly love, they delight to gaze on truth for its own sake. But how can those who insult their brethren in sorrow and deride them in joy possibly discern truth in their neighbours, seeing that they cannot enter into feelings of which they have no personal experience?",
        "The first food, then, is of humility, purgative with bitterness; the second of charity, consoling with sweetness; the third of contemplation, solid with strength. I have said, as I could, with what fruit the degrees of humility ought to be ascended; I will say, as I shall be able, in what order they lead to the proposed prize of truth. But because the recognition of truth itself also consists in three degrees, I distinguish them briefly, if I can, so that from this it may become clearer to which of the three of truth the twelfth of humility attains. For we seek the truth in ourselves, in neighbours, in its own nature. In ourselves, by judging ourselves; in neighbours, by suffering with their evils; in its own nature, by contemplating with a clean heart. Observe the number, and likewise the order. First let Truth itself teach you why it ought to be sought earlier in neighbours than in its own nature. After this you will receive why you ought to seek earlier in yourself than in neighbours. For in the number of the beatitudes, which he distinguished in his sermon, he placed the merciful before the clean of heart. The merciful quickly catch truth in neighbours, while they stretch their affections toward them, while they so conform themselves to them through charity that they feel their goods or evils as their own. With the weak they are weak, with the scandalized they burn. They have been accustomed to rejoice with those rejoicing, to weep with those weeping. By this fraternal charity the edge of the heart having been cleansed, they delight to contemplate the truth in its own nature, for love of which they bear others’ evils. But those who do not so associate themselves with the brothers, but on the contrary either insult those weeping or disparage those rejoicing — while they do not feel in themselves what is in them, because they are not similarly affected — how can they catch the truth in neighbours?",
      ),
      one(
        "p6",
        "6",
        "Bene namque convenit illis illud vulgare proverbium: Nescit sanus quid sentiat aeger, aut plenus quid patiatur ieiunus. Et aeger aegro, et ieiunus ieiuno quanto propinquius, tanto familiarius compatiuntur. Sicut enim pura veritas non nisi puro corde videtur, sic miseria fratris verius misero corde sentitur. Sed ut ob alienam miseriam cor miserum habeas, oportet tuam prius agnoscas, ut proximi mentem in tua invenias, et ex te noveris qualiter illi subvenias, exemplo scilicet Salvatoris nostri, qui pati voluit ut compati sciret, miser fieri ut misereri disceret, ut quomodo de ipso scriptum est: Et didicit ex his quae passus est oboedientiam (Hebr. v, 8), ita disceret, cuius misericordia ab aeterno et usque in aeternum; sed quod natura sciebat ab aeterno, temporali didicit experimento.",
        "Well, indeed, does the common saying fit them: ‘a healthy man has no idea of the feelings of one who is ill, nor does a well-fed man realize what a hungry man suffers.’ A sick man feels for the sick and a hungry man for the hungry, with familiarity the greater as his own condition approaches theirs. For as pure truth can be discerned only by one whose heart is pure, so can the sorrow of a brother be most truly felt by one whose heart is sad. But if your heart is to be saddened by the sorrows of others, you must recognize your own evil state, which you may see reproduced in your neighbour, and may thus know how to help him. And in this you have the example of our Saviour, who was willing to suffer that He might know how to sympathize, to accept sorrow that He might thus learn to pity. For, as it is written of Him, He learned obedience by the things which He suffered, so may He have suffered that He might learn compassion. This does not mean that He, whose compassion was eternal, had not hitherto known pity, but that what He knew in His nature in an eternal, He learned by experience in a temporal, sphere.",
        "For that common proverb fits them well: The healthy man does not know what the sick man feels, nor the full man what the fasting man suffers. And the sick with the sick, and the fasting with the fasting, the nearer they are, the more familiarly they suffer-with. For as pure truth is seen only by a pure heart, so a brother’s misery is more truly felt by a miserable heart. But that you may have a miserable heart on account of another’s misery, you must first recognize your own, that you may find the neighbour’s mind in yours, and from yourself know how you may help him — by the example, namely, of our Saviour, who willed to suffer that he might know how to suffer-with, to become miserable that he might learn to have mercy, so that, as it is written of him: And he learned obedience from the things which he suffered, so he might learn, whose mercy is from eternity and unto eternity; but what he knew by nature from eternity, he learned by a temporal experiment.",
        [
          {
            kind: "word",
            title: "miser / misereri",
            body: "Bernard’s pun is the argument: miser fieri ut misereri disceret. Mills splits it into ‘sorrow’ and ‘pity’. The close line keeps the same stem so the later two mercies (§12) remain audible.",
          },
        ],
      ),
      one(
        "p7",
        "7",
        "Sed forte durum tibi videtur, quod dixi Dei sapientiam Christum didicisse misericordiam, quasi is per quem omnia facta sunt, aliquid aliquando ignorasset ex his quae sunt, maxime cum illud quod ex epistola ad Hebraeos ad id comprobandum commemoravi, alio sensu, qui non ita videatur absurdus, possit intelligi, ut hoc quod dictum est, didicit, non ad ipsum caput referatur in sui persona, sed ad corpus eius, quod est Ecclesia, et sit ita sensus: Et didicit ex his quae passus est oboedientiam, hoc est: oboedientiam didicit in suo corpore his quae passus est in capite. Nam illa mors, illa crux, opprobria, sputa, flagella, quae omnia caput nostrum Christus pertransiit, quid aliud corpori eius, id est nobis, quam praeclara oboedientiae documenta fuerunt? Christus factus est, ait Paulus, oboediens Patri usque ad mortem (Phil. ii, 8). Qua necessitate? Respondeat apostolus Petrus: Christus passus est pro nobis, vobis relinquens exemplum, ut sequamini vestigia eius (I Petr. ii, 21), id est ut imitemini oboedientiam eius. Ex his ergo quae passus est, discimus quanta nos, qui puri homines sumus, oporteat pro oboedientia perpeti, pro qua is, qui et Deus erat, non dubitaverit mori. Et hoc modo, inquis, inconveniens non erit si dicitur Christus vel oboedientiam, vel misericordiam, seu aliquid aliud in suo corpore didicisse, dum tamen sibi in sui persona nil, quod se ante latuerit, credatur ex tempore potuisse accedere, sicque ipse sit qui misereri aut oboedire doceat, ipse qui discat, quia caput et corpus unus est Christus.",
        "But you may find it difficult to accept my statement that Christ who is the Divine wisdom learned compassion, as though it were possible for Him through whom all things were made ever to have been ignorant of anything; especially since the passage from Hebrews may be understood in a different sense. For, on this interpretation, the words ‘He learned’ would refer, not to His own Person, but to His body which is the Church. In that case He learned obedience in His body through what He personally suffered. For what was the meaning of that death, that cross, those insults, spittings and stripes, all of which Christ who is our head endured, unless that they afford to us who are His body convincing evidence of His obedience? Christ, saith Paul, became obedient to his Father, even unto death. And what was the need? Let Peter answer: Christ suffered for us leaving you an example that you should follow his steps — that is, that you should imitate His obedience. So from His sufferings we learn how much we who are mere men must be prepared to endure for obedience, in the exercise of which He, who is also God, did not hesitate to die. And this, you may say, is the sense in which it is not unreasonable to allege that Christ learned obedience or compassion in His body, although you believe that it was not possible for Him to acquire in His divine Person any knowledge He did not previously possess. Thus He might both learn and teach pity and obedience, since the head and the body is one Christ.",
        "But perhaps it seems hard to you, that I said Christ, the Wisdom of God, learned mercy, as if he through whom all things were made had at some time been ignorant of something among the things that are — especially since that which I recalled from the letter to the Hebrews to prove this can be understood in another sense, which may not seem so absurd: that this which was said, ‘he learned,’ is not referred to the head himself in his own person, but to his body, which is the Church, and the sense be this: And he learned obedience from the things which he suffered, that is: he learned obedience in his body by those things which he suffered in the head. For that death, that cross, the reproaches, the spit, the scourges, all of which Christ our head passed through — what else were they to his body, that is to us, than outstanding documents of obedience? Christ was made, says Paul, obedient to the Father even unto death. By what necessity? Let the apostle Peter answer: Christ suffered for us, leaving you an example, that you may follow his footsteps, that is, that you may imitate his obedience. From these things, then, which he suffered, we learn how great things we, who are mere men, ought to endure for obedience, for which he, who was also God, did not hesitate to die. And in this way, you say, it will not be unfitting if Christ is said to have learned either obedience or mercy or something else in his body, provided nevertheless it is believed that nothing which had previously been hidden from him could have acceded to him in his own person from time — and thus he himself is the one who teaches to have mercy or to obey, he himself who learns, because head and body is one Christ.",
      ),
      one(
        "p8",
        "8",
        "Non nego hunc intellectum, quin rectus sit; sed ex alio loco ipsius epistolae, superior interpretatio videtur approbari, ubi dicitur: Nusquam enim angelos apprehendit, sed semen Abrahae apprehendit; unde debuit per omnia fratribus similari, ut misericors fieret (Hebr. ii, 16–17). Puto quod haec verba sic ad caput referenda sint, ut corpori penitus aptari non possint. De Verbo utique Dei dictum est quod non angelos apprehendit, hoc est non unam sibi personam assumpsit, sed semen Abrahae. Neque enim legitur: Verbum angelus factum est, sed: Verbum caro factum est (Ioan. i, 14), et caro de carne Abrahae, iuxta promissionem quae illi primum facta est. Vnde, id est ex qua seminis assumptione, debuit per omnia fratribus similari, id est oportuit ac necesse fuit ut similis nobis passibilis, nostrarum omnia, excepto peccato, genera miseriarum percurreret. Si quaeris: Qua necessitate? Vt misericors, inquit. Et hoc, ais, cur non recte ad corpus referri potest? Sed audi quod paulo post sequitur: In eo enim, in quo passus est ipse et tentatus, potens est et eis qui tentantur auxiliari (Hebr. ii, 18). In quibus verbis quid melius intelligi possit non video, nisi quod ideo pati ac tentari, omnibusque, absque peccato, humanis voluit communicare miseriis — quod est per omnia fratribus similari — ut similiter passis ac tentatis misereri ac compati ipso disceret experimento.",
        "I do not deny that this verse may reasonably be thus understood. But the former interpretation seems to be supported by another passage in the same Epistle: For nowhere doth he take hold of the angels, but of the seed of Abraham he taketh hold, wherefore it behoved him in all things to be like unto his brethren, that he might become merciful. I think that these words have so close a reference to His Person that they cannot be altogether applicable to His body. It is said of the Word of God that He ‘took’, that is incorporated into His own personality, not angels but the seed of Abraham. For the passage reads not ‘the word was made an angel’ but the Word was made flesh, and that from the flesh of Abraham. Whereupon, by reason of this assumption of the seed, he ought in all things to be like unto his brethren — susceptible to suffering and sharing every kind of misfortune except sin. If you ask ‘Wherefore this necessity?’ the answer is that He may become merciful. And why may this not refer to His body? Listen to the words which closely follow: For in that wherein he himself hath suffered and been tempted, he is able to succour them also that are tempted. And for these words I can see no better meaning than that He was pleased thus to suffer and to be tempted and to associate Himself with all human misery except sin, in order that He might learn by personal experience to pity those who similarly suffer and are tempted.",
        "I do not deny this understanding, that it is not right; but from another place of the same letter the earlier interpretation seems to be approved, where it is said: For nowhere does he take hold of angels, but he takes hold of the seed of Abraham; whence he ought to be made like to the brothers in all things, that he might become merciful. I think that these words are so to be referred to the head that they cannot be fitted to the body at all. Of the Word of God it was certainly said that he did not take hold of angels, that is, he did not assume one person to himself, but the seed of Abraham. For it is not read: The Word was made an angel, but: The Word was made flesh, and flesh from the flesh of Abraham, according to the promise first made to him. Whence — that is, from which assumption of the seed — he ought to be made like to the brothers in all things, that is, it was right and necessary that, passible like us, he should run through all the kinds of our miseries, except sin. If you ask: By what necessity? That he might be merciful, he says. And this, you say, why can it not rightly be referred to the body? But hear what follows a little after: For in that in which he himself has suffered and been tempted, he is able also to help those who are tempted. In which words I do not see what can better be understood, except that he therefore willed to suffer and be tempted, and to share in all human miseries without sin — which is to be made like to the brothers in all things — that he might learn by the experiment itself to have mercy and to suffer-with those similarly having suffered and been tempted.",
      ),
      one(
        "p9",
        "9",
        "Quo quidem experimento non dico ut sapientior efficeretur, sed propinquior videretur, quatenus infirmi filii Adam, quos suos fieri et appellari fratres non dedignatus est, suas illi infirmitates committere non dubitarent, qui sanare illas et posset ut Deus, et vellet ut proximus, et cognosceret ut eadem passus. Vnde Isaias virum eum appellat dolorum, et scientem infirmitatem (Isai. liii, 3). Et Apostolus: Non enim habemus, inquit, pontificem, qui non possit compati infirmitatibus nostris (Hebr. iv, 15). Vnde autem possit, indicans adiungit: Tentatum autem per omnia pro similitudine, absque peccato. Beatus quippe Deus, beatus Dei Filius, in ea forma, qua non rapinam arbitratus est esse se aequalem Patri (Phil. ii, 6), procul dubio impassibilis, priusquam se exinanisset formam servi accipiens (Phil. ii, 7), sicut miseriam vel subiectionem expertus non erat, sic misericordiam vel oboedientiam experimento non noverat. Sciebat quidem per naturam, non autem sciebat per experientiam. At ubi minoratus est non solum a seipso, sed etiam paulo minus ab angelis (Hebr. ii, 9), qui et ipsi impassibiles sunt per gratiam, non per naturam, usque ad illam formam, in qua pati et subici posset, quod utique, sicut dictum est, in sua non posset, et in passione expertus est misericordiam, et in subiectione oboedientiam. Per quam tamen experientiam, non illi, ut dixi, scientia, sed nobis fiducia crevit, dum ex hoc misero genere cognitionis, is a quo longe erraveramus, factus est propior nobis. Quando enim illi appropinquare auderemus, in sua impassibilitate manenti? Nunc autem, Apostolo suadente, monemur cum fiducia adire thronum gratiae ipsius (Hebr. iv, 16), quem nimirum, sicut alibi scriptum est, languores nostros tulisse et dolores portasse cognoscimus (Isai. liii, 4), et in eo quo passus est ipse, nobis compati posse non dubitamus.",
        "I do not say that this experience added to His knowledge, but that it brought Him closer to us, so that the weak sons of Adam whom He has not disdained to make His own and to call His brethren need not hesitate to bring their infirmities to Him, who, recognizing what He has Himself endured, as God is able and as their neighbour is desirous to provide the remedy. For this reason Isaiah calls Him a man of sorrows and acquainted with infirmity, and the Apostle says, We have not a High Priest who cannot have compassion on our infirmities. And to show how He can have such compassion the writer adds, but one tempted in all things like as we are, without sin. For surely the blessed God, while in that form in which He thought it not robbery to be equal with the Father, was beyond doubt incapable of suffering before He had emptied Himself and taken the form of a slave; and as He had no experience of sorrow or of subjection, He had no opportunity of practising either compassion or obedience. He had indeed a natural but not an experimental knowledge of these. Yet as He was made a little lower than the angels, who by favour not by nature are incapable of suffering, He took a form in which it was possible for Him to suffer and to submit. Thus by suffering He learned compassion and by subjection obedience. This experience led to an increase, not of Wisdom on His part, but of confidence on ours, since by the knowledge thus painfully acquired He from whom we had been so widely separated was brought nearer to us. For when would we dare to approach Him while He was incapable of suffering? But now the Apostle exhorts us to go with confidence to the throne of grace, whereon is He who hath borne our infirmities and carried our sorrows, and of whose power to sympathize with us in what He has himself endured we can entertain no doubt.",
        "By which experiment I do not say that he was made wiser, but that he might seem nearer, so that the weak sons of Adam, whom he did not disdain to become and to be called his brothers, might not hesitate to commit their infirmities to him, who both could heal them as God, and would as neighbour, and knew as one who had suffered the same. Whence Isaiah calls him a man of sorrows, and one knowing infirmity. And the Apostle: For we do not have a high priest who cannot suffer-with our infirmities. Indicating whence he can, he adds: But tempted through all things according to likeness, without sin. For the blessed God, the blessed Son of God, in that form in which he did not judge it robbery to be equal to the Father, was beyond doubt impassible, before he had emptied himself, taking the form of a slave; as he had not experienced misery or subjection, so he had not known mercy or obedience by experiment. He knew indeed through nature, but he did not know through experience. But when he was made less not only than himself, but also a little less than the angels, who themselves are impassible through grace, not through nature, even to that form in which he could suffer and be subjected, which indeed, as has been said, he could not in his own, he also experienced mercy in the passion, and obedience in subjection. Yet through which experience, not knowledge for him, as I said, but trust for us grew, while from this miserable kind of knowing, he from whom we had wandered far was made nearer to us. For when would we dare to approach him, remaining in his impassibility? Now, however, the Apostle persuading, we are warned to go with trust to the throne of his grace, whom we know, as it is written elsewhere, to have borne our weaknesses and carried our sorrows, and we do not doubt that he can suffer-with us in that in which he himself has suffered.",
      ),
      one(
        "p10",
        "10",
        "Non ergo debet absurdum videri, si dicitur Christum non quidem aliquid scire coepisse, quod aliquando nescierit, scire tamen alio modo misericordiam ab aeterno per divinitatem, et aliter in tempore didicisse per carnem. Vide ne et simili locutionis modo illud dictum sit, quod Domino requirentibus discipulis de die ultimo se nescire respondit. Nam quomodo diem illum ille nesciebat, in quo omnes thesauri sapientiae et scientiae sunt absconditi (Coloss. ii, 3)? Cur ergo se scire negabat, quod certum est quia nescire non poterat? Numquid forte mendaciter eos voluit celare, quod utiliter non valuit innotescere? Absit. Sicut nil ignorare poterat, cum sapientia sit: sic nec mentiri, cum veritas sit. Sed volens discipulos ab inutilis inquisitionis curiositate compescere, quod inquirebant se scire negavit: non omnimodo quidem, sed tali quodam modo, quo negare veraciter potuit. Nam, etsi suae divinitatis intuitu aeque omnia, praeterita scilicet, praesentia atque futura perlustrando, diem quoque illum palam habebat; non tamen ullis carnis suae sensibus experiendo agnoverat. Alioquin iam spiritu oris sui Antichristum interfecerat, iam auribus sui corporis archangelum vociferantem, et tubam sonantem, in quo strepitu mortui suscitandi sunt, audierat: iam oculis suae carnis oves haedosque, qui ab invicem segregandi sunt, perspexerat.",
        "So there appears to be no contradiction in saying that, as there is nothing of which Christ was ever unaware, His knowledge could have no commencement, and, on the other hand, in maintaining that while in His Divine nature He knew compassion from all eternity, in another capacity He learned it under bodily and temporal conditions. And note the similar language which our Lord used when in reply to a question from His disciples He pleaded ignorance of the date of the Last Day. For how could He in whom are hid all the treasures of wisdom and knowledge be unaware of that day? How could He, for whom ignorance of any sort was clearly impossible, say that He did not know? Could He possibly desire to conceal by a subterfuge information which He could not profitably disclose? God forbid! For neither could He who is Wisdom be unaware of anything, nor could He who is Truth be capable of falsehood. But in His desire to discourage the useless curiosity of the disciples, He pleaded ignorance of the matter about which they asked Him — not indeed without qualification but in a way in which He could truthfully disclaim such knowledge. For although by His Divine insight — ranging over all things past, present and future — He had that day clearly before Him, it was still true that He was unaware of it by the exercise of any bodily sense. Had it been otherwise He would already have slain Antichrist with the breath of His mouth, would have heard with His bodily ears the shout of the archangel and the sound of the trumpet at whose call the dead are to rise, and would have surveyed with His bodily eyes the sheep and the goats who are then to be separated from each other.",
        "It ought not, then, to seem absurd if it is said that Christ did not indeed begin to know something which he had at some time not known, yet that he knew mercy in one way from eternity through divinity, and learned it otherwise in time through the flesh. See whether that also was said in a similar manner of speaking, that the Lord, the disciples asking about the last day, answered that he did not know. For how did he not know that day, in whom all the treasures of wisdom and knowledge are hidden? Why then did he deny that he knew what it is certain he could not not-know? Did he perhaps wish falsely to hide from them what he could not usefully make known? Far from it. As he could be ignorant of nothing, since he is wisdom, so neither could he lie, since he is truth. But wishing to restrain the disciples from the curiosity of a useless inquiry, he denied that he knew what they were asking: not in every manner indeed, but in a certain such manner in which he could deny truthfully. For although by the insight of his divinity, surveying equally all things — past, namely, present and future — he also had that day openly; yet he had not come to know it by experiencing with any senses of his flesh. Otherwise he would already have killed Antichrist with the spirit of his mouth, would already have heard with the ears of his body the archangel crying out and the trumpet sounding, in which noise the dead are to be raised: already with the eyes of his flesh he would have looked upon the sheep and the kids who are to be separated from one another.",
      ),
    ],
  },
];
