import { one, paragraph, segment, type Chapter } from "../../schema";

export const chaptersLater: Chapter[] = [
  {
    id: "cap-4",
    number: 4,
    title: "Caput IV",
    heading: "Primum veritatis gradum, primum seipsum attendere",
    paragraphs: [
      one(
        "p11",
        "11",
        "Denique, ut intelligas quod illa tantum cognitione, quae per carnem fit, se illum diem nescire perhibuerit, vigilanter respondens, non ait: Nec ego scio, sed: Nec ipse, inquit, Filius hominis scit. Quid est Filius hominis, nisi nomen assumptae carnis? Quo siquidem nomine intelligi datur, quia dicens se aliquid nescire, non iuxta quod Deus est, sed secundum hominem loquitur. Alias quippe loquens de se secundum suam deitatem, non filius vel filium hominis, sed Ego vel me, saepius ponere consuevit, ut ibi: Amen, amen dico vobis, antequam Abraham fieret, ego sum. Ego sum, ait, non: Filius hominis est. Nec dubium, quin de illa essentia diceret, qua ante Abraham et sine initio est, non qua post Abraham et ex Abraham factus est. Alibi quoque hominum de se opinionem a discipulis inquirens: Quem dicunt, inquit, homines esse, non me, sed Filium hominis? Rursus eosdem interrogans, quid de se ipsi quoque sentirent: Vos autem, non quem Filium hominis, sed quem me, ait, esse dicitis? Carnalis videlicet populi sententiam de carne inquirens, nomen carnis, quod proprie est Filius hominis, posuit; spirituales vero discipulos de sua divinitate interrogans, non Filium hominis, sed signanter me dixit. Quod denique Petrus intelligens, quid per hoc quod dixerat, me, requisiti fuissent, sua responsione aperuit: Tu es, inquiens, non Iesus filius Virginis, sed Christus Filius Dei (Matth. xvi, 13–16). Quod utique si respondisset, nihilominus veritatem dixisset: sed in verbis interrogationis sensum interrogantis prudenter advertens, competenter proprieque ad interrogata respondit, dicens: Tu es Christus, Filius Dei.",
        "But with the intention of making it clear that it was only in the sphere of that intelligence which He possessed in His human capacity that he asserted His ignorance of that day, He was careful in His answer not to say ‘I do not know’ but ‘The Son of Man himself doth not know.’ Now what is this title of ‘Son of Man’ but the one which He assumed on taking on Himself our nature? By its use here, He means it to be understood that when He says that He is ignorant of anything, He is speaking not as God, but as man. When on the other hand He refers to His own Godhead, He usually says not ‘the Son’ or ‘the Son of Man’ but ‘I’ or ‘me’ — as in the passage verily verily I say unto you, before Abraham was made, I am. He there speaks of Himself as ‘I’ not as the ‘Son of Man’. And when He elsewhere asks His disciples what men think of Him, He says Whom do men say not ‘that I am’ but that the Son of Man is? But when He afterwards asks the same disciples what they themselves felt about Him, He says, But whom do you say not ‘that the Son of Man is,’ but that I am? So when He asks the opinion of worldly persons about His bodily nature He uses the term ‘Son of Man,’ but when He questions His spiritual followers about His Godhead, He significantly says not ‘the Son of Man’ but ‘me’. And that Peter understood what He meant is apparent from his reply: Thou art, not ‘Jesus the son of a Virgin,’ but Christ the Son of God. Had he made the former reply he would have said what is no less true. But shrewdly gathering from the wording of the question the meaning of Him who put it, he gave a suitable and sufficient answer by saying, Thou art Christ the Son of God.",
        "Finally, that you may understand that he alleged himself not to know that day only by that knowledge which is made through the flesh, answering watchfully, he does not say: Nor do I know, but: Nor does the Son of man himself, he says, know. What is the Son of man, if not the name of the assumed flesh? By which name indeed it is given to be understood that, saying he does not know something, he speaks not according as he is God, but according to the man. For otherwise, speaking of himself according to his deity, he was accustomed more often to set not son or son of man, but I or me, as there: Amen, amen I say to you, before Abraham was made, I am. I am, he says, not: The Son of man is. Nor is there doubt that he was speaking of that essence by which he is before Abraham and without beginning, not that by which after Abraham and from Abraham he was made. Elsewhere also, inquiring from the disciples the opinion of men about himself: Whom do men say is, he says, not me, but the Son of man? Again asking the same what they themselves also felt about him: But you, not whom the Son of man, but whom me, he says, do you say that I am? Seeking the carnal people’s sentence about the flesh, he set the name of the flesh, which properly is Son of man; but asking the spiritual disciples about his divinity, he said not the Son of man, but signally me. Which Peter at last understanding — what they had been asked by this that he had said, me — opened by his answer: You are, saying, not Jesus son of the Virgin, but Christ the Son of God. Which indeed if he had answered, he would nevertheless have said the truth: but in the words of the question prudently noticing the sense of the one asking, he answered the things asked fittingly and properly, saying: You are Christ the Son of God.",
        [
          {
            kind: "text",
            title: "Mills follows Bernard’s misquotation",
            body: "The retractatio admits the Gospel has only Filius. Mills still translates Bernard’s Nec ipse Filius hominis scit. This is not Mills inventing; it is Bernard’s Latin as written, later confessed.",
          },
        ],
      ),
      one(
        "p12",
        "12",
        "Cum igitur videas Christum in una quidem persona duas habere naturas, unam qua semper fuit, alteram qua esse coepit; et secundum sempiternum quidem suum esse, semper omnia nosse; secundum temporale vero, multa temporaliter expertum fuisse: cur fateri dubitas, ut esse ex tempore coepit in carne, sic carnis quoque miserias scire coepisse, illo dumtaxat modo cognitionis, quem docet defectio carnis? Quod utique genus scientiae protoplasti sapientius feliciusque nescirent, quando ad attingere nisi stulte misereque non poterant. Sed plasmator eorum Deus requirens quod perierat, opus suum miseratus prosecutus est, descendens et ipse misericorditer, quo illi ceciderant miserabiliter. Voluit experiri in se, quod illi faciendo contra se merito paterentur, non simili quidem curiositate, sed mirabili charitate: non ut miser cum miseris remaneret, sed ut misericors factus miseros liberaret. Factus, inquam, misericors, non illa misericordia, quam felix manens habuit ab aeterno, sed quam mediante miseria reperit in habitu nostro. Porro pietatis opus, quod per illam coepit, in ista perfecit: non quod sola illa non posset perficere, sed quia nobis non potuit absque ista sufficere. Vtraque siquidem necessaria, sed nobis haec magis congrua fuit. O ineffabilis pietatis excogitatio! Quando illam adverteremus incognitam nobis compassionem, quae non passione praeventa, cum impassibilitate perdurat? Attamen si illa quae miseriam nescit, misericordia non praecessisset, ad hanc, cuius miseria mater est, non accessisset. Si non accessisset, non attraxisset; si non attraxisset, non extraxisset. Vnde autem extraxit, nisi de lacu miseriae et de luto faecis (Psal. xxxix, 3)? Nec illam tamen misericordiam deseruit, sed hanc inseruit; non mutavit, sed multiplicavit, sicut scriptum est: Homines et iumenta salvabis, Domine, quemadmodum multiplicasti misericordiam tuam, Deus (Psal. xxxv, 7–8).",
        "Now from this you may see that Christ has two natures, albeit in one Person, one in which He has always existed, the other in which He had a beginning, and that while in that nature which is eternal He always knew everything, in that which is temporal He found out many things in the course of time. Why then do you find it difficult to admit that as there was a time when His bodily existence began, so may His knowledge of the ills of the flesh — at all events that sort of knowledge which bodily weakness conveys — have had a beginning? Our first parents would no doubt have been better and wiser had they not possessed knowledge of this sort, since they could acquire it only through folly and misfortune. But God, their Creator, seeking what had been lost, in His mercy followed up His own handiwork. He Himself mercifully descended to the level from which they had miserably fallen, and was willing Himself to endure what they deservedly suffered — not from a curiosity like theirs, but from marvellous love, His purpose being not to remain in misery with the unfortunate, but to become merciful and so to deliver them. When I say that he became merciful I refer not to that compassion which had been His in His eternal condition of bliss, but to that which He acquired through the medium of misfortune, while He bore our nature. Moreover, He completed in the latter the work of love which He had commenced in the former state. He could undoubtedly have made it complete in the former alone, but without the latter it would not have been effectual for us. Both forms were essential, but the latter more closely concerns ourselves. How indescribable is the method of His goodness. Could we ever have understood that marvellous mercy unless previous suffering had given it shape? Could we have discerned His sympathy, of which we had no knowledge, if He had had no previous suffering and had remained insusceptible to pain? Yet had He not possessed that compassion which knows no misfortune, He would never have attained that whose mother is misfortune. If He had not attained this He could not have drawn it to Himself. If He had not so drawn it, He could not have brought it out. And whence did He bring it out if not from the pit of misery and mire of dregs? Yet He did not abandon that earlier compassion, but added to it the later. He did not alter He augmented it, as it is written, Men and beasts thou wilt preserve, O God, O how hast thou multiplied thy mercy, O God.",
        "When therefore you see that Christ has two natures in one person indeed, one by which he always was, the other by which he began to be; and according to his everlasting being, always to know all things; but according to the temporal, to have experienced many things temporally: why do you hesitate to confess that, as he began to be in the flesh from time, so he also began to know the miseries of the flesh, in that manner of knowing only which the failing of the flesh teaches? Which kind of knowledge the first-formed would more wisely and more happily not have known, since they could not attain it except stupidly and miserably. But God their fashioner, seeking what had perished, having mercy followed his work, himself descending mercifully to where they had fallen miserably. He willed to experience in himself what they, by doing against him, deservedly suffered — not by a like curiosity, but by marvellous charity: not that a miserable one might remain with the miserable, but that, having been made merciful, he might free the miserable. Made, I say, merciful, not by that mercy which, remaining blessed, he had from eternity, but by that which, misery mediating, he found in our habit. Further, the work of piety, which he began through the former, he completed in the latter: not that the former alone could not complete it, but because for us it could not suffice without this. Both were necessary, but for us this was more fitting. O unspeakable thinking-out of piety! When would we have noticed that compassion unknown to us, which, not forestalled by passion, endures with impassibility? Yet if that which does not know misery had not had mercy, that whose mother is misery would never have followed. If it had not followed, it would not have drawn. If it had not drawn, it would not have led out. And from where did it lead out, if not from the lake of misery and from the mud of dregs? Yet he did not lose that former mercy, but added this. He did not change, he increased, as it is written: Men and beasts you will save, Lord; as you have multiplied your mercy, O God.",
        [
          {
            kind: "theology",
            title: "two mercies",
            body: "illa misericordia … quam felix manens habuit ab aeterno versus quam mediante miseria reperit. Mills says ‘compassion’ both times. Bernard’s pair is the same word, distinguished by how it is had.",
          },
        ],
      ),
      one(
        "p13",
        "13",
        "Sed iam ad propositum redeamus. Si ergo se miserum fecit, qui miser non erat, ut experiretur quod et ante sciebat: quanto magis tu, non dico ut te facias quod non es, sed ut attendas quod es, quia vere miser es, et sic discas misereri, qui hoc aliter scire non potes? Ne forte, si proximi malum consideres, et tuum non attendas, movearis non ad miserationem, sed ad indignationem; non ad adiuvandum, sed ad iudicandum: denique non ad instruendum in spiritu lenitatis, sed ad destruendum in spiritu furoris. Vos, qui spirituales estis, ait Apostolus, huiusmodi instruite in spiritu lenitatis. Apostoli consilium sive etiam praeceptum est, ut mansueto, id est eo spiritu fratri aegrotanti subvenias, quod tibi vis subveniri cum aegrotas. Et ut scias qualiter erga delinquentem mansuescere possis: Considerans, inquit, teipsum, ne et tu tenteris (Galat. vi, 1).",
        "But let us resume the thread of our argument. If then He in whose nature there was no sadness, made Himself sad in order that He might have personal experience of something of the existence of which He was already aware, how much more is it your duty, I will not say to alter, but to recognize your condition, which is indeed a pitiable one — and thus to learn compassion of which you could otherwise have no knowledge? For it may well happen that by dwelling on the shortcomings of your neighbour without sufficient attention to your own, you may be moved not to pity but to anger — not to assist but to condemn, and so to destroy in a spirit of wrath, rather than to restore in a spirit of meekness. Ye who are spiritual, saith the Apostle, instruct such an one in the spirit of meekness. The counsel — aye, the command — of the Apostle is that you should aid your ailing brother in the same kindly spirit in which you would wish to be helped when you are ailing. And to show how it is possible to be forbearing towards a wrong-doer, he says, considering thyself lest thou also be tempted.",
        "But now let us return to the proposed matter. If therefore he made himself miserable who was not miserable, that he might experience what he also knew before: how much more you — I do not say that you make yourself what you are not, but that you attend to what you are, because you are truly miserable, and so learn to have mercy, you who cannot otherwise know this? Lest perhaps, if you consider the neighbour’s evil and do not attend to yours, you be moved not to pity but to indignation; not to helping but to judging: finally not to instructing in the spirit of gentleness, but to destroying in the spirit of fury. You who are spiritual, says the Apostle, instruct such in the spirit of gentleness. It is the Apostle’s counsel or even precept, that you help a sick brother with the meek, that is that spirit, with which you wish to be helped when you are sick. And that you may know how you can grow meek toward the delinquent: Considering, he says, yourself, lest you also be tempted.",
      ),
      one(
        "p14",
        "14",
        "Considerare libet, quam bene discipulus Veritatis ordinem sequatur Magistri. In beatitudinibus, quas supra memoravi (num. 6), sicut prius misericordes quam mundicordes, sic prius mites quam misericordes pronuntiati sunt (Matth. v, 4, 7, 8). Et Apostolus cum spirituales hortaretur ad instruendum carnales, adiunxit: in spiritu lenitatis. Instructio quippe fratrum pertinet ad misericordes; spiritus lenitatis, ad mites. Ac si diceret: Inter misericordes deputari non potest, qui in semetipso mitis non est. Ecce Apostolus aperte ostendit, quod superius me ostensurum promisi (num. 6), prius videlicet veritatem inquirendam esse in nobis, quam in proximis; considerans, inquiens, teipsum, id est, quam facilis ad tentandum, quam pronus ad peccandum: quatenus ex tui consideratione mitescas, sicque ad succurrendum aliis in spiritu lenitatis accedas. Alioquin si monentem non audis discipulum, arguentem time Magistrum: Hypocrita, eice primum trabem de oculo tuo, et tunc videbis festucam eicere de oculo fratris tui (Matth. vii, 5). Trabes in oculo grandis et grossa, superbia in mente est, quae quadam corpulentia sui vana, non sana, tumida, non solida, oculum mentis obscurat, veritatem obumbrat, ita ut si tuam occupaverit mentem, iam tu te videre, iam te talem, qualis es, vel qualis esse potes, non possis sentire, sed qualem te amas, talem te vel putes esse, vel speres fore. Quid enim aliud est superbia, quam, ut quidam sanctus definit, amor propriae excellentiae? Vnde et nos possumus dicere, per contrarium, humilitatem propriae excellentiae esse contemptum. Amor vero, sicut nec odium, veritatis iudicium nescit. Vis iudicium Veritatis audire? Sicut audio, sic iudico: non sicut odi, non sicut amo, non sicut timeo. Est iudicium odii, ut illud: Nos legem habemus, et secundum legem nostram debet mori. Est et timoris, ut illud: Si dimittimus eum sic, venient Romani et tollent nostrum locum et gentem. Iudicium vero amoris, ut David de filio parricida: Parcite, inquit, puero Absalon. Et legibus humanis statutum, et in causis, tam ecclesiasticis quam saecularibus servatum scio, speciales amicos causantium non debere admitti ad iudicium, ne vel fallant vel fallantur amore suorum. Quod si culpam amici tuo iudicio amor illius aut minuit, aut prorsus abscondit, quanto magis amor tui tuum contra te iudicium fallit?",
        "And please to note how well the disciple of Truth follows the sequence of the Master. In the Beatitudes the ‘merciful’ are named before the ‘pure in heart’, as are the ‘meek’ before the ‘merciful’. And the Apostle when he exhorted those who were spiritual to restore such as were carnal, added in the spirit of meekness. For the reformation of the brethren is the mark of the merciful, and a spirit of meekness that of the humble. He says in effect that no one who is not himself meek can be reckoned among the merciful. Note that the Apostle here clearly asserts that truth must be sought in ourselves before we can look for it in others, for he says consider thyself. If, however, you heed not the warning of the Apostle, tremble before the rebuke of the Master. Thou hypocrite, cast out first the beam out of thine own eye. Pride in the mind is like a thick heavy beam in the eye, whose excessive size is due not to health but to vanity, to swelling rather than to strength. It so darkens the mental vision as to hide the truth. For what is pride if not — as a certain holy man defines it — ‘appreciation of one’s own goodness’? If this be so, we may say, on the other hand, that humility is the disparagement of our own goodness. For love and hatred alike ignore the verdict of truth. Would you like to hear what that verdict is? As I hear so I judge, not as ‘I hate’ or ‘I love’ nor as ‘I fear’. There is the judgment of hate, such as that which said We have a law and according to our law he ought to die. And there is the judgment of fear like that one If we let him alone so the Romans will come and take away our place and nation. But there is a judgment of love, as that of David on the son who would have slain his father, Spare the boy Absalom. And I know that it is a rule of human law, which is binding alike in ecclesiastical and in civil actions, that personal friends of the litigants shall not be allowed to take part in the proceedings lest through their affection for their friends they may be misled or may mislead others. And if affection for a friend leads you to extenuate or even to conceal his guilt, how much more will self-esteem preclude an unfavourable verdict upon yourself?",
        "It is pleasant to consider how well the disciple of Truth follows the order of the Master. In the beatitudes which I recalled above, as first the merciful were pronounced before the clean of heart, so first the meek before the merciful. And the Apostle, when he exhorted the spiritual to instruct the carnal, added: in the spirit of gentleness. For the instruction of the brothers belongs to the merciful; the spirit of gentleness, to the meek. As if he said: He cannot be counted among the merciful who is not meek in himself. See, the Apostle openly shows what I promised above I would show, namely that the truth is to be sought earlier in us than in neighbours; saying, considering yourself, that is, how easy to be tempted, how prone to sinning: so that from consideration of yourself you may grow meek, and so approach to helping others in the spirit of gentleness. Otherwise if you do not hear the disciple warning, fear the Master arguing: Hypocrite, cast out first the beam from your eye, and then you will see to cast out the speck from your brother’s eye. The beam in the eye, large and thick, is pride in the mind, which by a certain corpulence of itself — vain, not sound, swollen, not solid — darkens the eye of the mind, overshadows the truth, so that if it shall have occupied your mind, you can no longer see yourself, no longer feel yourself such as you are, or such as you can be, but such as you love yourself, such you either think yourself to be, or hope to be. For what else is pride than, as a certain holy man defines, the love of one’s own excellence? Whence we also can say, by the contrary, that humility is the contempt of one’s own excellence. But love, as neither hatred, does not know the judgment of truth. Do you wish to hear the judgment of Truth? As I hear, so I judge: not as I hate, not as I love, not as I fear. There is a judgment of hatred, as that: We have a law, and according to our law he ought to die. There is also of fear, as that: If we dismiss him thus, the Romans will come and take away our place and nation. But a judgment of love, as David about a parricide son: Spare, he says, the boy Absalom. And I know it established by human laws, and kept in causes both ecclesiastical and secular, that special friends of those pleading ought not to be admitted to judgment, lest they either deceive or be deceived by love of their own. But if the love of a friend either lessens his fault by your judgment, or wholly hides it, how much more does love of yourself deceive your judgment against you?",
      ),
      one(
        "p15",
        "15",
        "Qui ergo plene veritatem in se cognoscere curat, necesse est ut, semota trabe superbiae, quae oculum arcet a luce, ascensiones in corde suo disponat, per quas in seipso seipsum inquirat, et sic post duodecimum humilitatis ad primum veritatis gradum pertingat. Cum autem veritate inventa in se, immo se invento in veritate, dicere potuerit: Credidi, propter quod locutus sum; ego autem humiliatus sum nimis: ascendat homo ad cor altum, ut exaltetur veritas, et ad gradum secundum perveniens dicat in excessu suo: Omnis homo mendax.",
        "So the man who is really anxious to discover the truth about himself must remove the beam of pride which prevents him from seeing the light, and must propose in his heart to ascend by steps by which he may scrutinize his inmost self, and from the twelfth degree of humility may pass on to the first degree of truth. But when a man has found truth in himself — or rather has found himself in truth — so that he can say, I have believed and therefore have I spoken, but I have been humbled exceedingly, he may rise to a high spiritual level in order that truth may be held up, and may say in his ecstasy, Every man is a liar.",
        "He therefore who cares to know the truth fully in himself must, the beam of pride having been removed which keeps the eye from the light, arrange ascents in his heart, through which he may seek himself in himself, and so after the twelfth of humility attain to the first degree of truth. But when, the truth having been found in himself — nay rather, himself having been found in the truth — he shall have been able to say: I believed, for which I spoke; but I was humbled exceedingly: let the man ascend to a high heart, that the truth may be exalted, and arriving at the second degree say in his going-out: Every man is a liar.",
        [
          {
            kind: "word",
            title: "in excessu suo",
            body: "Mills’s ‘ecstasy’ is one medieval sense of excessus. Bernard’s word is also simply a going-out of oneself. The close line keeps going-out so the Pharisee’s later excessus can be the same term used badly.",
          },
        ],
      ),
    ],
  },
  {
    id: "cap-5",
    number: 5,
    title: "Caput V",
    heading: "Secundus gradus veritatis est, ex agnitione propria misereri proximi",
    paragraphs: [
      one(
        "p16",
        "16",
        "Humiliatus ergo Propheta in hoc primo gradu veritatis, ut ait in alio Psalmo: Et in veritate tua humiliasti me, semetipsum attendat, et ex propria miseria generalem perpendat, sicque ad secundum transiens, dicat in excessu suo: Omnis homo mendax. In quo excessu suo? In illo, procul dubio, quo sese excedens ac veritati adhaerens, seipsum diiudicat. In illo ergo excessu suo dicat, non indignando aut insultando, sed miserando et compatiendo: omnis homo infirmus, omnis homo miser et impotens, qui nec se, nec alium possit salvare. Sicut dicitur: Fallax equus ad salutem, non quod equus aliquem fallat, sed quia is seipsum fallit, qui in fortitudine eius confidit, sic omnis homo dicitur mendax, id est fragilis, mutabilis, a quo salus non possit vel sua, vel aliena sperari, quin potius maledictionem incurrat, qui spem suam in homine ponit (Ierem. xvii, 5). Proficiens itaque humilis Propheta per ducatum veritatis, quodque in se lugebat videns in aliis, dum apponit scientiam, apponat et dolorem, ac generaliter, sed veraciter dicat: Omnis homo mendax.",
        "Thus in this, the first degree of Truth, the Prophet is so humbled that he says in another Psalm, In thy truth thou hast humbled me. He may then reasonably conclude that the wretched condition in which he finds himself to be, is that of mankind in general. And as he thus passes into the second degree, he may say in his ecstasy, Every man is a liar. And in what does this ecstasy consist? Is it not without doubt due to the fact that in his detachment from himself and attachment to truth, he pronounced his own condemnation? So in that ecstatic condition he may say, not in anger or insult but with pity and regret, Every man is a liar. Every man is weak, every man is poor and powerless, since none can save himself or any one else. In much the same sense is it said, Vain is the horse for safety, not because the horse deceives anyone but because the rider deceives himself if he relies on the horse’s strength. So every man is said to be false, that is, fragile and fickle. Thus the humble Prophet, proceeding under the guidance of Truth, observes in other people what he mourns in himself; where he finds knowledge he will also find sorrow, and so may say broadly but truly, Every man is a liar.",
        "The Prophet therefore, humbled in this first degree of truth, as he says in another Psalm: And in your truth you have humbled me, let him attend to himself, and from his own misery weigh the general, and so passing to the second, let him say in his going-out: Every man is a liar. In which going-out of his? In that, far from doubt, in which, going out of himself and clinging to the truth, he judges himself. In that going-out of his, then, let him say, not by being indignant or insulting, but by pitying and suffering-with: every man is weak, every man miserable and powerless, who can save neither himself nor another. As it is said: A deceitful horse for salvation — not that the horse deceives anyone, but because he deceives himself who trusts in its strength — so every man is called a liar, that is fragile, changeable, from whom neither his own nor another’s salvation can be hoped, but rather he incurs a curse who places his hope in man. The humble Prophet therefore, advancing by the leading of truth, seeing in others what he was mourning in himself, while he adds knowledge, let him also add grief, and generally but truly say: Every man is a liar.",
      ),
      one(
        "p17",
        "17",
        "Vide quam longe aliud senserit de se Pharisaeus ille superbus. Quid deprompsit in excessu suo? Deus, gratias ago tibi, quia non sum sicut ceteri hominum (Luc. xviii, 11). Dum in se singulariter exsultat, aliis arroganter insultat. David autem aliter. Ait enim: Omnis homo mendax. Neminem excipit, ne quem decipiat: sciens quia omnes peccaverunt, et omnes egent gloria Dei (Rom. iii, 23). Pharisaeus se solum decipit, quem solum excipit, dum ceteros damnat. Propheta se non excipit a communi miseria, ne excipiatur a misericordia: Pharisaeus exsufflat misericordiam, dum dissimulat miseriam. Propheta affirmat tam de omnibus, quam de se: Omnis homo mendax: Pharisaeus confirmat de omnibus praeter se, Non sum, inquiens, sicut ceteri hominum. Et gratias agit, non quia bonus, sed quia solus: non tam de bonis quae habet, quam de malis quae in aliis videt. Nondum de suo trabem eiecerat, et festucas in oculis fratrum enumerat. Nam subdit: iniusti, raptores (Luc. xviii, 11). Non frustra, ut arbitror, excessum a proposito feci, si utriusque excessus differentiam intellexisti.",
        "Now note how widely different was the tone of that haughty Pharisee. What was the purport of his ill-considered utterance? God, I give thee thanks that I am not as the rest of men. While he is strangely satisfied with himself, he is offensively rude to others. David takes quite another line. He says Every man is a liar. He will make no exceptions which might be misleading, for he knows that all have sinned and all do need the glory of God. The Pharisee, while condemning others, claims exemption for himself alone. The Prophet does not exempt himself from the general guilt, lest he be excluded from mercy. The Pharisee stifles mercy by his disclaimer of guilt. The Prophet asserts, of himself as of every one, Every man is false. The Pharisee endorses this of all except himself. And he returns thanks not that he is good, but that he stands alone — not so much for his own merits as for the ill which he sees in others. He has not yet cast out the beam out of his own eye, but he reckons up the motes in the eyes of his brethren. I think that this diversion from the subject may not have been without its value, if it has enabled you to appreciate the difference between these two utterances.",
        "See how far otherwise that proud Pharisee felt about himself. What did he draw forth in his going-out? God, I give you thanks, because I am not like the rest of men. While he exults in himself as singular, he arrogantly insults others. But David otherwise. For he says: Every man is a liar. He excepts no one, lest he deceive someone: knowing that all have sinned, and all lack the glory of God. The Pharisee deceives himself alone, whom alone he excepts, while he condemns the rest. The Prophet does not except himself from the common misery, lest he be excepted from mercy: the Pharisee blows away mercy, while he conceals misery. The Prophet affirms as much about all as about himself: Every man is a liar: the Pharisee confirms it about all besides himself, saying, I am not like the rest of men. And he gives thanks, not because he is good, but because he is alone: not so much for the goods he has, as for the evils he sees in others. He had not yet cast the beam from his own, and he enumerates specks in the brothers’ eyes. For he adds: unjust, robbers. Not in vain, as I judge, have I made a going-out from the purpose, if you have understood the difference of each going-out.",
      ),
      one(
        "p18",
        "18",
        "Iam ad propositum redeundum est. Quos itaque Veritas sibi iam innotescere, ac per hoc vilescere fecit, necesse est, ut cuncta, quae amare solebant, et ipsi sibi amarescant. Statuentes nimirum se ante se, tales se videre cogunt, quales vel a se videri erubescunt. Dumque sibi displicet quod sunt, et ad id suspirant quod non sunt, quod utique per se fore diffidunt, vehementer sese lugentes, id solum consolationis inveniunt, ut severi iudices sui, qui scilicet amore veri esuriant et sitiant iustitiam, usque ad contemptum sui districtissimam de se sententiam ferant. Qui cum ad id sufficere non posse conspiciunt — cum enim fecerint omnia quae mandata fuerint sibi, servos se inutiles dicunt — de iustitia ad misericordiam fugiunt. Vt autem illam consequantur, consilium Veritatis sequuntur: Beati misericordes, quoniam ipsi misericordiam consequentur. Et hic est secundus gradus veritatis, quo eam in proximis inquirunt, dum de suis aliorum necessitates exquirunt, dum ex his quae patiuntur, patientibus compati sciunt.",
        "Let us now return to the main subject. If truth thus compels men to look into themselves and so to learn their own worthlessness, it follows that all those things which have hitherto given them pleasure — yea, even their own selves — should become distasteful to them. For as they sit in judgment upon themselves, they cannot fail to see themselves in a light in which they are ashamed to be seen even by their own eyes. Their present condition displeases them and they long to be what they are not. Yet they find their consolation in the fact that their judgment of themselves has been stern; and they hope that their hunger and thirst after righteousness — even to the point of self contempt — will enable them to exact a strict satisfaction. But when they perceive their incapacity, and realize that when they have done all that is commanded they must still call themselves unprofitable servants, they fly from justice to mercy. And that they may obtain this they follow the advice given by Truth, Blessed are the merciful, for they shall obtain mercy. This then is the second degree of truth, the one in which men look for it in their neighbours — when from the realization of their own shortcomings they discover those of other people and learn from their own painful experience to sympathize with those who suffer.",
        "Now one must return to the purpose. Those, then, whom Truth has already made known to themselves, and through this made cheap, it is necessary that all things which they were accustomed to love should also grow bitter to themselves. Setting themselves before themselves, they compel themselves to see themselves such as they blush to be seen even by themselves. And while what they are displeases them, and they sigh toward that which they are not, which they distrust can be through themselves, mourning themselves vehemently, they find this only of consolation: that as severe judges of themselves, who namely by love of the true hunger and thirst for justice, they bear a most strict sentence about themselves even to contempt of themselves. Who, when they see they cannot suffice for this — for when they have done all things that shall have been commanded them, they call themselves useless servants — flee from justice to mercy. But that they may obtain that, they follow the counsel of Truth: Blessed are the merciful, because they themselves will obtain mercy. And this is the second degree of truth, by which they seek it in neighbours, while from their own they search out the needs of others, while from those things which they suffer they know how to suffer-with those suffering.",
      ),
    ],
  },
  {
    id: "cap-6",
    number: 6,
    title: "Caput VI",
    heading: "Tertius veritatis gradus, ad quem pervenitur mundato corde",
    paragraphs: [
      one(
        "p19",
        "19",
        "In his ergo tribus quae dicta sunt, id est in luctu paenitentiae, in desiderio iustitiae, in operibus misericordiae si perseverant, a tribus impedimentis, quae aut ignorantia, aut infirmitate, aut studio contraxerunt, cordis aciem mundant, quo per contemplationem ad tertium veritatis gradum pertranseant. Hae sunt viae, quae videntur hominibus bonae, illis dumtaxat qui laetentur cum male fecerint, et exsultant in rebus pessimis, ac se de infirmitate vel ignorantia tegunt ad excusandas excusationes in peccatis. Sed frustra sibi de infirmitate vel ignorantia blandiuntur, qui ut liberius peccent, libenter ignorant vel infirmantur. Qui igitur studio et amore peccandi a veritate se sentiunt alienatos, infirmitate et ignorantia pressos, studium in gemitum, amorem in maerorem convertant. Ab omni ergo labe, infirmitate, ignorantia, studiove contracta, flendo, iustitiam esuriendo, operibus misericordiae insistendo, mundatur oculus cordis, cui se in sui puritate videndam Veritas promittit: Beati enim mundo corde, quoniam ipsi Deum videbunt. Cum sint itaque tres gradus seu status veritatis, ad primum ascendimus per laborem humilitatis, ad secundum per affectum compassionis, ad tertium per excessum contemplationis. In primo veritas reperitur severa; in secundo pia, in tertio pura. Ad primum ratio ducit, qua nos discutimus; ad secundum affectus perducit, quo aliis miseremur; ad tertium puritas rapit, qua ad invisibilia sublevamur.",
        "If therefore men practise perseverance in the sorrow of repentance, the longing for righteousness, and works of mercy, they clear their spiritual sight of the three hindrances which either through ignorance, infirmity or disposition they have encountered, and may thus pass on to that direct vision in which the third degree of truth consists. These are the ways that seem good to men — at all events to those who are glad when they have done evil and rejoice in most wicked things, and who attempt to cover their sins with the cloak of ignorance or of weakness. But vainly do they whose ignorance or weakness is wilful put forward either of these pleas. Let such persons turn inclination into aversion; let them conquer the weakness of the flesh by righteous energy, and dispel ignorance by better education. Thus by the tears of penitence, by the pursuit of righteousness and by persistence in works of mercy, is the spiritual sight cleared. And to it truth promises to reveal itself in its purity. Blessed are the clean of heart, for they shall see God. There are then three kinds or degrees of truth; we rise to the first by humble effort, to the second by loving sympathy, to the third by enraptured vision. In the first truth is revealed in severity, in the second in pity, in the third in purity. Reason, by which we analyze ourselves, guides us to the first; feeling which enables us to pity others conducts us to the second; purity by which we are raised to the level of the unseen, carries us up to the third.",
        "In these three things, then, that have been said — that is, in the mourning of penitence, in the desire of justice, in the works of mercy — if they persevere, they cleanse the edge of the heart from the three impediments which they contracted either by ignorance, or by infirmity, or by zeal, so that through contemplation they may pass through to the third degree of truth. These are the ways that seem good to men, to those only who rejoice when they have done evil, and exult in the worst things, and cover themselves from infirmity or ignorance to make excuses in sins. But they flatter themselves in vain about infirmity or ignorance, who, that they may sin more freely, willingly are ignorant or are weak. Those therefore who feel themselves alienated from the truth by the zeal and love of sinning, pressed by infirmity and ignorance, let them turn zeal into groaning, love into grief. From every stain, then, contracted by infirmity, ignorance, or zeal, by weeping, by hungering for justice, by pressing on in works of mercy, the eye of the heart is cleansed, to which Truth promises herself to be seen in her purity: For blessed are the clean of heart, because they themselves will see God. Since therefore there are three degrees or states of truth, we ascend to the first through the labour of humility, to the second through the affection of compassion, to the third through the going-out of contemplation. In the first the truth is found severe; in the second pious, in the third pure. Reason leads to the first, by which we discuss ourselves; affection leads through to the second, by which we have mercy on others; purity snatches to the third, by which we are lifted to invisible things.",
      ),
    ],
  },
  {
    id: "cap-7",
    number: 7,
    title: "Caput VII",
    heading: "Quomodo sancta Trinitas hos tres veritatis gradus operetur",
    paragraphs: [
      one(
        "p20",
        "20",
        "Interlucet hic mihi mira quaedam ac divisa individuae Trinitatis operatio, si quo modo tamen ab homine sedente in tenebris ineffabilis illa possit capi cooperantium sibi personarum divisio. In primo siquidem gradu Filius, in secundo Spiritus sanctus, in tertio Pater operari videtur. Vis audire Filii operationem? Si ego, inquit, lavi vos pedes Dominus et magister, quanto magis et vos debetis alter alterius lavare pedes (Ioan. xiii, 14, 15)? Tradebat discipulis humilitatis formam veritatis Magister, qua in primo gradu primum eis veritas innotesceret. Attende et opus Spiritus sancti: Charitas Dei diffusa est in cordibus nostris per Spiritum sanctum qui datus est nobis (Rom. v, 5). Charitas quippe donum est Spiritus sancti, qua fit ut qui sub disciplina Filii per humilitatem ad primum usque gradum veritatis iam profecerunt, ad secundum per compassionem proximi, sub magisterio Spiritus sancti perveniant. Audi et de Patre. Beatus es, Simon Bar Iona, quia caro et sanguis non revelavit tibi, sed Pater meus qui in caelis est (Matth. xvi, 17); et illud: Pater filiis notam faciet veritatem suam (Isai. xxxviii, 19); et: Confiteor tibi, Pater, quia abscondisti haec a sapientibus et revelasti ea parvulis (Matth. xi, 25). Vides quia quos verbo et exemplo prius Filius humiliavit, super quos deinde Spiritus sanctus charitatem effudit, hos tandem in gloria Pater recepit? Filius facit discipulos, Paraclitus consolatur amicos, Pater exaltat filios. Quia vero non solum Filius, sed et Pater et Spiritus sanctus veraciter Veritas appellantur, constat quod una eademque Veritas, servata proprietate personarum, tria haec in tribus gradibus operatur. Primo scilicet instruit, ut magister; secundo consolatur, ut amicus vel frater; tertio astringit, ut filios pater.",
        "Here I seem to discern a certain marvellous and individual operation of each Person of the Trinity — if indeed it is possible for the limited intelligence of man to conceive a difference such as cannot be expressed in words between persons who co-operate. On this supposition, the first degree appears to be due to the action of the Son, the second to that of the Holy Spirit, and the third to that of the Father. Would you wish to hear about the work of the Son? If, saith He, I, your Lord and Master, have washed your feet, how much more ought ye to wash one another’s feet. The Master of truth thus presented to His disciples a pattern of humility, that they might therein discern the first degree of truth. Mark also the work of the Holy Spirit, Love is poured forth in our hearts by the Holy Ghost which is given to us. Love is indeed the gift of the Holy Spirit, and this makes it possible for those who, under the instruction of the Son, have by humility already attained the first degree of truth, under the guidance of the Holy Spirit to reach the second by sympathy with their neighbours. Hear also what is said about the Father. Blessed art thou Simon Bar Jona, because flesh and blood hath not revealed it to thee, but my father who is in heaven. And there is another passage, The father shall make thy truth known to the children. And yet again, I thank thee, Father, because thou hast hid these things from the wise and hast revealed them to little ones. You see then how the Father at last receives into glory those to whom the Son first taught humility, and on whom the Holy Spirit then shed love. The Son receives them as learners, the Comforter encourages them as friends, the Father raises them as sons. From this it follows that one and the same truth — preserving the characteristics of each of the Persons — performs this threefold work in the three degrees. In the first it gives instruction as does a master; in the second it affords counsel as does a friend or a brother; in the third it provides a bond of union as does a father to his sons.",
        "Here a certain wondrous and divided operation of the undivided Trinity shines through to me, if nevertheless that ineffable division of the persons cooperating with themselves can in any way be grasped by a man sitting in darkness. In the first degree indeed the Son, in the second the Holy Spirit, in the third the Father seems to work. Do you wish to hear the Son’s operation? If I, he says, the Lord and master, washed your feet, how much more ought you also to wash one another’s feet? The Master of truth was handing to the disciples the form of humility, by which in the first degree the truth might first become known to them. Attend also to the work of the Holy Spirit: The charity of God has been poured out in our hearts through the Holy Spirit who has been given to us. For charity is the gift of the Holy Spirit, by which it comes about that those who under the discipline of the Son through humility have already advanced even to the first degree of truth, arrive at the second through compassion for the neighbour, under the teaching of the Holy Spirit. Hear also about the Father. Blessed are you, Simon Bar-Jona, because flesh and blood has not revealed to you, but my Father who is in the heavens. and that: The Father will make his truth known to the sons; and: I confess to you, Father, because you have hidden these from the wise and have revealed them to little ones. Do you see that those whom the Son first humbled by word and example, upon whom the Holy Spirit then poured out charity, these at last the Father received in glory? The Son makes disciples, the Paraclete consoles friends, the Father exalts sons. Because truly not only the Son, but also the Father and the Holy Spirit are truly called Truth, it is established that one and the same Truth, the property of the persons having been kept, works these three things in the three degrees. First, namely, it instructs, as a master; second it consoles, as a friend or brother; third it binds, as a father his sons.",
      ),
      one(
        "p21",
        "21",
        "Dei quippe Filius, Verbum scilicet ac sapientia Patris, primum quidem illam animae nostrae potentiam, quae ratio dicitur, cum reperit carne depressam, peccato captivam, ignorantia caecam, exterioribus deditam, clementer assumens, potenter erigens, prudenter instruens, introrsum trahens, ac mirabiliter utens tanquam pro se vicaria, ipsam sibi iudicem statuit, ita ut pro reverentia Verbi cui coniungitur, ipsa sui accusatrix, testis et iudex, contra se Veritatis fungatur officio. Ex qua prima coniunctione Verbi et rationis, humilitas nascitur. Aliam deinde partem, quae dicitur voluntas, veneno quidem carnis infectam, sed iam ratione discussam, Spiritus sanctus dignanter visitans, suaviter purgans, ardenter afficiens, misericordem facit: ita ut more pellis, quae uncta extenditur, ipsa quoque unctione perfusa caelesti, usque ad inimicos per affectum dilatetur. Et sic ex hac secunda coniunctione Spiritus Dei et voluntatis humanae, charitas efficitur. Vtramque vero partem, rationem scilicet ac voluntatem, alteram verbo veritatis instructam, alteram spiritu veritatis afflatam; illam hyssopo humilitatis aspersam, hanc igne charitatis succensam; tandem iam perfectam animam, propter humilitatem sine macula, propter charitatem sine ruga, cum nec voluntas rationi repugnat, nec ratio veritatem dissimulat, gloriosam sibi sponsam Pater conglutinat: ita ut nec ratio de se, nec voluntas de proximo cogitare sinatur, sed hoc solum beata illa anima dicere delectetur: Introduxit me Rex in cubiculum suum. Digna certe, quae de schola humilitatis, in qua primum sub magistro Filio ad seipsam intrare didicit, iuxta comminationem ad se factam: Si ignoras te, egredere et pasce haedos tuos, digna ergo quae de schola illa humilitatis, duce Spiritu sancto, in cellaria charitatis (quae nimirum proximorum pectora intelligenda sunt) per affectionem introduceretur, unde suffulta floribus ac stipata malis, bonorum scilicet moribus et virtutibus sanctis, ad Regis demum cubiculum, cuius amore languet, admitteretur. Ibi modicum, hora videlicet quasi dimidia, silentio facto in caelo, inter desideratos amplexus suaviter quiescens ipsa quidem dormit, sed cor eius vigilat, quo utique interim veritatis arcana rimatur, quorum postmodum memoria statim ad se reditura pascatur. Ibi videt invisibilia, audit ineffabilia, quae non licet homini loqui.",
        "Thus the Son of God — that is to say the word and wisdom of the Father — first found that intellectual faculty of yours which is called reason, fettered by the flesh, a captive to sin, blinded by ignorance, and surrendered to things external. In His mercy He took it up, by His power He raised it, by His wisdom He taught it, drew it to Himself, and in a marvellous manner made it His representative. He then caused it so to sit in judgment upon itself that, with due reverence to the Word with whom it was associated, it might act as its own accuser, witness and judge. It is from this first alliance between the Word and reason that humility has its origin. We then come to the second faculty, which is called will, contaminated by the poison of the flesh, though this has already been in a measure counteracted by reason. This the Holy Spirit honours with a visit, administers to it a gentle purgative, imparts to it a genial warmth, and thus renders it compassionate. in such a way that after the fashion of a skin which is stretched by the application of an ointment, so the will that has been treated with the heavenly ointment may be so expanded as to become friendly to those that were its enemies. And this second alliance between the spirit of God and the will of man produces love. The Father finally takes the two faculties reason and will — the one taught by the Word and sprinkled with the hyssop of humility, the other inspired by the spirit of truth and influenced by the fire of love — and unites them into a perfect soul, from which humility has removed all wrinkles and in which love has left no stain. In it will resists not reason, nor does reason trifle with truth, for the Father unites it to Himself as His glorious bride, in such a way that reason may not be allowed to think of itself, nor will of its neighbour, but the entire delight of that blessed soul will be to say, The king has taken me into his chamber. It was fitting that that soul should first learn in the school of humility under the tuition of the Son, to enter into herself in accordance with the warning given. If thou knowest not thyself, go forth and feed thy kids. Thus did she become fit to be brought from the school of humility under the guidance of the Holy Spirit through affection into the store rooms of love by which undoubtedly is meant the hearts of her neighbours. Thence, seated on flowers and surrounded by friends, that is by good habits and holy virtues, she may at last gain entrance to the chamber of the King, for whose love she longs. There, when silence has been made in heaven for a space, it may be of half an hour, she rests calmly in those dear embraces — herself asleep, but her heart on the watch how she may in the present range over those regions of hidden truth — on whose memory she will feast as soon as she returns to herself — there she sees things invisible and hears things unutterable, of which it is not lawful for man to speak.",
        "For the Son of God, namely the Word and wisdom of the Father, first that power of our soul which is called reason, when he found it pressed down by the flesh, captive to sin, blind by ignorance, given to exterior things, taking it up clemently, raising it powerfully, instructing it prudently, drawing it inward, and marvellously using it as a vicar for himself, set it as judge for itself, so that for reverence of the Word to which it is joined, itself accuser, witness and judge of itself, it may discharge the office of Truth against itself. From which first conjunction of the Word and reason, humility is born. Then the other part, which is called will, infected indeed by the poison of the flesh, but already discussed by reason, the Holy Spirit, visiting it worthily, purging it sweetly, affecting it ardently, makes merciful, so that after the manner of a hide, which being anointed is stretched, it also, poured over with a heavenly unction, may be dilated even unto enemies through affection. And so from this second conjunction of the Spirit of God and the human will, charity is effected. But both parts, namely reason and will, the one instructed by the word of truth, the other breathed upon by the spirit of truth; that one sprinkled with the hyssop of humility, this one kindled by the fire of charity; at last the already perfect soul, because of humility without stain, because of charity without wrinkle, when neither will resists reason, nor reason disguises the truth, the Father glues to himself as a glorious bride, so that neither reason is allowed to think about itself, nor will about the neighbour, but that blessed soul delights to say this only: The King has brought me into his chamber. Worthy certainly, who from the school of humility, in which first under the master the Son she learned to enter into herself, according to the threat made to herself: If you do not know yourself, go out and feed your kids, worthy therefore who from that school of humility, the Holy Spirit leading, would be led through affection into the cellars of charity (which indeed are to be understood as the breasts of neighbours), whence, supported by flowers and packed with apples, namely by the manners of the good and holy virtues, she would at last be admitted to the chamber of the King, for whose love she languishes. There a little, namely for an hour as if a half, silence having been made in heaven, sweetly resting among the desired embraces she herself indeed sleeps, but her heart watches, by which meanwhile she searches the secrets of truth, on whose memory afterwards, about to return at once to herself, she may be fed. There she sees invisible things, hears unspeakable things, which it is not permitted a man to speak.",
      ),
    ],
  },
  {
    id: "cap-8",
    number: 8,
    title: "Caput VIII",
    heading: "Paul caught up to the third heaven",
    paragraphs: [
      one(
        "p22",
        "22",
        "Putas hos gradus Paulus non transierat, qui usque ad tertium caelum se raptum fuisse dicebat? Sed quare raptum, et non potius ductum? Vt videlicet si tantus Apostolus raptum se dicit fuisse, quo nec doctus scivit, nec ductus potuit ire, me, qui procul dubio minor sum Paulo, ad tertium caelum nulla mea virtute, nullo meo labore pervenire posse praesumam, ne vel de virtute confidam, vel pro labore diffidam. Qui enim docetur aut ducitur, ex hoc ipso quod docentem vel ducentem sequitur, laborare convincitur, et aliquid de se agit, ut ad destinatum vel locum vel sensum pertrahatur, ita ut dicere possit: Non autem ego, sed gratia Dei mecum (I Cor. xv, 10). Qui vero rapitur, non suis viribus, sed alienis innixus, tanquam nescius, quocumque portatur, nec cum alio aliquid operatur. Ad primum itaque sive ad medium caelum ductus vel adiutus Apostolus ascendere potuit; ad tertium autem ut perveniret, rapi oportuit. Nam et Filius ad hoc legitur descendisse, ut iuvaret ascensuros ad primum, et Spiritus sanctus missus fuisse, qui perduceret ad secundum. Pater vero, licet Filio et Spiritui sancto semper cooperetur, numquam tamen aut de caelo descendisse, aut ad terras legitur missus fuisse. Lego certe, quod misericordia Domini plena est terra, et pleni sunt caeli et terra gloria tua, et multa huiuscemodi. Lego et de Filio: Postquam venit plenitudo temporis, misit Deus Filium suum; et ipse Filius loquitur de se: Spiritus Domini misit me. Lego et de Spiritu sancto: Paraclitus autem Spiritus sanctus, quem mittet Pater in nomine meo. Patrem autem in sua persona, licet nusquam non sit, nusquam tamen invenio nisi in caelis, ut in Evangelio: Et Pater meus qui in caelis est (Matth. xvi, 17); et in oratione: Pater noster qui es in caelis (Matth. vi, 9).",
        "Do you suppose that St. Paul had not undergone the same gradual process when, as he has told us, he was ‘caught up’ to the third heaven? But why was he ‘caught up’ instead of being ‘led up’? The reason surely was that if so great an Apostle says that he was ‘caught up’ to a place whither no teaching nor leading could bring him, I, who am certainly a lesser man than Paul, may not venture to think that I can reach the third heaven by any strength or effort of my own. For a man who is taught or led is obliged, from the fact that he follows his teacher or leader, to use some effort. He at all events does enough to enable him to say, Not I but the grace of God with me. But the man who is carried away, not by his own action, but by that of others, cannot take the credit or any part of it to himself. The Apostle might possibly have been directed or assisted to the first or to the middle heaven; to reach the third one he had to be caught up. For the Son is said to have come down for the purpose of helping men to rise to the first, and the Holy Spirit to have been sent to lead them to the second. But the Father, though He always co-operates with the Son and the Holy Spirit, is never said to have come down from heaven, or to have been sent to the earth. It is true that the earth is full of the mercy of the Lord, and that heaven and earth are full of thy glory, and much to the same effect. And of the Son I read, when the fulness of the time came, God sent his Son, and the Son Himself says of Himself, The Spirit of the Lord hath sent me. And of the Holy Spirit I read, The Paraclete, the Holy Ghost, whom the Lord will send in my name. But though there is no region in which the Father does not exist, I find no mention of His own Person anywhere but in heaven, as in the Gospel, my father who is in heaven, and in the prayer, Our Father who art in heaven.",
        "Do you think Paul had not passed these degrees, who was saying that he had been snatched even to the third heaven? But why snatched, and not rather led? Namely so that if so great an Apostle says that he was snatched, whither neither taught did he know how to go, nor led could he go, I, who am beyond doubt less than Paul, may not presume that I can arrive at the third heaven by no virtue of mine, by no labour of mine — lest I either trust in virtue, or distrust because of labour. For he who is taught or led, from this very thing that he follows the one teaching or leading, is convicted of labouring, and does something of himself, that he may be drawn through to the destined place or sense, so that he can say: Yet not I, but the grace of God with me. But he who is snatched, leaning not on his own strengths but on another’s, as if unknowing, is carried wherever, nor does he work anything with another. To the first, then, or to the middle heaven the Apostle could ascend led or helped; but that he might arrive at the third, it was necessary that he be snatched. For the Son also is read to have descended for this, that he might help those who would ascend to the first, and the Holy Spirit to have been sent, who might lead through to the second. But the Father, although he always cooperates with the Son and the Holy Spirit, is nevertheless never read either to have descended from heaven, or to have been sent to the lands. I read certainly that the earth is full of the mercy of the Lord, and heaven and earth are full of your glory, and many of this kind. I read also of the Son: After the fullness of time came, God sent his Son; and the Son himself speaks of himself: The Spirit of the Lord sent me. I read also of the Holy Spirit: But the Paraclete the Holy Spirit, whom the Father will send in my name. But the Father in his own person, although he is nowhere not, I nevertheless nowhere find except in the heavens, as in the Gospel: And my Father who is in the heavens; and in the prayer: Our Father who are in the heavens.",
      ),
      one(
        "p23",
        "23",
        "Vnde nimirum colligo, quod, quia Pater non descendit, Apostolus, ut eum videret, ad tertium caelum ascendere quidem non potuit, quo tamen se raptum memoravit. Denique: Nemo ascendit in caelum, nisi qui descendit de caelo, Filius hominis (Ioan. iii, 13). Et ne putes de primo dictum vel secundo, dicit tibi David: A summo caelo egressio eius (Psal. xviii, 7). Ad quod iterum non subito raptus, non furtim sublatus, sed: Videntibus, inquit, illis, id est Apostolis, elevatus est. Non sicut Elias, qui unum, non sicut Paulus, qui nullum (vix enim vel seipsum testem aut arbitrum habere potuit, ipso perhibente: Nescio, Deus scit, II Cor. xii, 2): sed ut Omnipotens, qui quando voluit descendit, quando voluit ascendit, pro suo arbitrio arbitros et spectatores, locum et tempus, diem et horam exspectans, videntibus illis, quos scilicet tanta visione dignatur, elevatus est. Raptus est Paulus, raptus est Elias, translatus est Enoch (Eccli. xliv, 16): Redemptor vero noster legitur elevatus, hoc est, ex seipso levatus, non aliunde adiutus. Denique non currus vehiculo, non angeli adminiculo, sed propria virtute subnixum suscepit eum nubes ab oculis eorum (Act. i, 9). Cur hoc? An fessum iuvat? an pigrum impulit? an cadentem sustinuit? Absit. Sed suscepit eum ab oculis carnalibus discipulorum: qui, etsi Christum noverant secundum carnem, sed ultra iam non noscerent. Quos ergo per humilitatem ad primum caelum Filius vocat, hos in secundo per charitatem Spiritus aggregat, ad tertium per contemplationem Pater exaltat. Primo humiliantur in veritate, et dicunt: In veritate tua humiliasti me.",
        "From this I unhesitatingly conclude that as the Father did not come down, the Apostle could not go up to the third heaven in order to see Him, though he recalls that he was ‘caught up’ thither. Moreover, No man hath ascended into heaven but he that descended from heaven. And lest you should suppose that the reference here is to the first or second heaven, David tells you, His going out is from the end of heaven. And to this He was not suddenly caught up, or secretly conveyed, but, as is stated, in their sight he was raised up. It was not with Him, as with Elias who had one witness, or with Paul who could have none, to attest his statement, and who could hardly do so himself, for he admits I know not, God knoweth. But as the Almighty, He descended and ascended as He pleased, and chose at His discretion, the place, the time, the day and the hour, as well as the onlookers whom He thought worthy to be the witnesses of so great a spectacle, and while they looked on he was raised up. Elias and Paul were caught up; Enoch was translated; our Saviour is said to have been taken up, that is to have gone up by Himself, without help from anyone. He depended neither on conveyance by a chariot, or assistance by an angel, but on His own power. A cloud received him out of their sight. And what was the purpose of this cloud? Was it to help Him in weakness, to stimulate Him in slackness, or to sustain Him when in danger of falling? Such ideas are inconceivable. That cloud received Him out of the bodily sight of His disciples who, though they had known Him as Christ in the flesh, did not as yet know Him to be more than man. So those whom the Son calls through humility to the first heaven, the Spirit brings together by love in the second, and the Father raises by direct vision to the third. In the first they are humbled by the truth and say, In thy truth thou hast humbled me.",
        "Whence I gather, of course, that, because the Father did not descend, the Apostle, that he might see him, could not indeed ascend to the third heaven, to which nevertheless he recalled that he was snatched. Finally: No one has ascended into heaven, except he who descended from heaven, the Son of man. And lest you think it said of the first or the second, David says to you: His going-out is from the highest heaven. To which again he was not suddenly snatched, not secretly taken up, but: While they were seeing, he says, that is the Apostles, he was elevated. Not as Elias, who had one, not as Paul, who had none (for he could scarcely have even himself as witness or arbiter, himself attesting: I do not know, God knows): but as the Almighty, who when he willed descended, when he willed ascended, awaiting according to his judgment arbiters and spectators, place and time, day and hour, with those seeing, whom namely he deigns with so great a vision, he was lifted. Paul was snatched, Elias was snatched, Enoch was transferred: but our Redeemer is read as elevated, that is, lifted from himself, not helped from elsewhere. Finally not by the vehicle of a chariot, not by the help of an angel, but supported by his own power a cloud received him from their eyes. Why this? Does it help him tired? did it push the sluggish? did it sustain the falling? Far be it. But it received him from the carnal eyes of the disciples: who, even if they had known Christ according to the flesh, yet would already not know him further. Those therefore whom the Son calls through humility to the first heaven, these in the second the Spirit gathers through charity, to the third the Father exalts through contemplation. First they are humbled in the truth, and they say: In your truth you have humbled me.",
      ),
    ],
  },
  {
    id: "cap-9",
    number: 9,
    title: "Caput IX",
    heading: "Gemitus et suspiria sancti Bernardi, ad veritatem anhelantis",
    paragraphs: [
      one(
        "p24",
        "24",
        "Sed quid ego miser, superflua magis loquacitate quam spiritus vivacitate, duos caelos superiores percurro, qui manibus pedibusque repens adhuc sub inferiore laboro? Ad quod tamen iam, ipso iuvante, quo et vocante, mihi scalam erexi. Illic siquidem iter est, quo ostendat mihi salutare Dei. Iam Dominum desuper innixum suspicio, iam ad vocem Veritatis exsulto. Vocavit me, et ego respondi illi: Operi manuum tuarum porriges dexteram. Tu quidem, Domine, gressus meos dinumeras, sed ego lentus ascensor, fessus viator, diverticula quaero. Vae mihi, si tenebrae me comprehendant, aut si mea fuga fiat in hieme, vel in sabbato, dum nunc ad lucem, cum tempus acceptabile et dies salutis sunt, proficisci dissimulo. Quid moror? Ora pro me, fili, frater, socie, et particeps profectus mei, si quis es, in Domino. Ora Omnipotentem, quatenus sic pigrum roboret pedem, ut tamen non veniat mihi pes superbiae. Etsi enim pes piger, ut ad veritatem ascendat, idoneus non est; tolerabilior est tamen isto, qui in ea stare non potest, ut habes ibi: Expulsi sunt, nec potuerunt stare.",
        "But how can a poor creature like myself ramble on about the two higher heavens in a way more suggestive of the outpouring of words than of spiritual activity, seeing that it is as much as I can do to crawl on my hands and feet under the lower one? Yet I have already, with the help of Him who calls me, set up for myself a ladder to that higher level. Now I look upwards to the Lord who is leaning over me, now I spring forward at the call of truth. He has called me and I have answered Him, to the work of thine hands thou shalt reach out thy right hand. Thou, Lord, dost indeed number my steps, but I, slow climber and tired traveller, am looking for a resting place by the way. Woe is unto me if the darkness gets hold of me, or if my flight be in the winter or on the sabbath day, yet, though now is the acceptable time, I delay to set forth towards the light. Why do I thus hold back? Pray for me, son, brother, friend, fellow traveller with me in the Lord — if such there be. Pray to the Almighty that He will strengthen my feeble foot, yet in such a way that the foot of pride may not come to me. For though my foot is feeble and unable to attain to the truth, it is more reliable than one which, when it has reached it, cannot stand therein.",
        "But why I, miserable, more by superfluous talkativeness than by liveliness of spirit, run through the two higher heavens, I who, creeping with hands and feet, still labour under the lower? To which nevertheless already, himself helping, by whom also calling, I have erected a ladder for myself. For there is the journey, by which he may show me the salvation of God. Already I look up to the Lord leaning from above, already I exult at the voice of Truth. He called me, and I answered him: You will stretch out the right hand to the work of your hands. You indeed, Lord, number my steps, but I, a slow climber, a tired traveller, seek by-ways. Woe to me, if the darkness should seize me, or if my flight should happen in winter, or on the sabbath, while now I pretend not to set out toward the light, when it is the acceptable time and the day of salvation. Why do I delay? Pray for me, son, brother, companion, and sharer of my progress, if you are anyone, in the Lord. Pray the Almighty, that he so strengthen the sluggish foot, that nevertheless the foot of pride may not come to me. For even if a sluggish foot is not fit to ascend to the truth, it is nevertheless more tolerable than that one which cannot stand in it, as you have there: They were expelled, nor could they stand.",
      ),
      one(
        "p25",
        "25",
        "Et hoc quidem de superbis. Sed quid de illorum capite? Quid de illo, qui dicitur rex super omnes filios superbiae? Et ipse, inquit, in veritate non stetit. Et alibi: Videbam Satanam cadentem de caelo. Quare hoc, nisi propter superbiam? Vae mihi, si et me viderit, qui alta a longe cognoscit, superbientem: et illam in me terribilem intonet vocem: Tu quidem filius Excelsi eras, sed sicut homo morieris, et sicut unus de principibus cades. Quis non ab huius tonitrui voce formidet? O quam salubrius ad tactum Angeli nervus femoris Iacob emarcuit, quam angeli superbientis intumuit, evanuit, ruit. Vtinam et meum nervum Angelus tangat ut marcescat, si forte ex hac infirmitate incipiam proficere, qui ex mea firmitate non possum nisi deficere. Lego profecto: Quod infirmum est Dei, fortius est hominibus (I Cor. i, 25). Sic quoque Apostolus de suo nervo conquestus, quem angelus non Domini, sed Satanae colaphizabat, responsum audivit: Sufficit tibi gratia mea, nam virtus in infirmitate perficitur. Quae virtus? Ipse Apostolus respondeat: Libenter gloriabor in infirmitatibus meis, ut inhabitet in me virtus Christi (II Cor. xii, 9). Sed nondum forsitan intelligis, de qua specialiter dixerit, quia Christus omnes virtutes habuit. Sed cum omnes habuerit, prae omnibus tamen unam, id est humilitatem, nobis in se commendavit, cum ait: Discite a me, quia mitis sum et humilis corde (Matth. xi, 29).",
        "So much for the proud. But what about their chief? What about him who is called king over all the children of pride? He, said the Master, stood not in the truth, and elsewhere, I saw Satan falling from heaven. Why did he thus fall, unless on account of pride? Woe be to me if he who knoweth the high afar off should see me also indulging in pride, and should launch at me the terrible sentence, Thou wast indeed the son of the most high, but as a man thou shalt die, and thou shalt fall like one of the princes. Who would not quail before this voice of thunder? O how much better it was for Jacob that the sinew of his thigh shrank at the touch of the angel than that it should swell, weaken and perish at that of the messenger of pride. Would that an angel would touch my sinew and make it shrink, so that I, who in my own strength cannot but fail, may from my weakness begin to make progress. I surely read, The weakness of God is stronger than men. So also did the Apostle, when he complained of the sinew which an angel, not of God but of Satan, was buffeting, receive the reply, My grace is sufficient for thee for virtue is made perfect in infirmity. What is this virtue? Let the Apostle himself give the answer, Gladly therefore will I glory in mine infirmity, that the virtue of Christ may dwell in me. But you may not quite understand to what virtue he particularly alludes, since Christ possesses all the virtues. But though He has them all, there is one which He pre-eminently possesses and specially commends to us, namely, humility, for He says, Learn of me because I am meek and humble of heart.",
        "And this indeed about the proud. But what about their head? What about him who is called king over all the sons of pride? And he, he says, did not stand in the truth. And elsewhere: I was seeing Satan falling from heaven. Why this, if not because of pride? Woe to me, if he also shall have seen me, who knows high things from afar, growing proud: and shall thunder that terrible voice upon me: You indeed were a son of the Most High, but you will die like a man, and you will fall like one of the princes. Who would not fear from the voice of this thunder? O how more healthfully at the angel’s touch the sinew of Jacob’s thigh withered, than that of the proud angel swelled, vanished, rushed down. Would that an Angel might also touch my sinew that it may wither, if perhaps from this infirmity I may begin to advance, I who from my firmness can only fail. I read indeed: What is weak of God is stronger than men. So also the Apostle, having complained of his sinew, which an angel not of the Lord but of Satan was buffeting, heard the answer: My grace is sufficient for you, for power is perfected in infirmity. Which power? Let the Apostle himself answer: Gladly I will glory in my infirmities, that the power of Christ may dwell in me. But perhaps you do not yet understand about which he spoke specially, because Christ had all powers. But although he had all, yet before all he commended one to us in himself, that is humility, when he says: Learn from me, because I am meek and humble of heart.",
      ),
      one(
        "p26",
        "26",
        "Libenter igitur et ego, Domine Iesu, gloriabor, si potero, in mea infirmitate, in mei nervi contractione, ut tua virtus, id est humilitas, perficiatur in me. Nam sufficit mihi gratia tua, cum defecerit virtus mea. Pedem profecto gratiae fortiter figens, et meum, qui infirmus est, leniter trahens, securus ascendam per scalam humilitatis, donec veritati adhaerens, ad latitudinem transeam charitatis. Tunc psallam cum gratiarum actione, et dicam: Statuisti in loco spatioso pedes meos. Sic arcta via cautius strictim inceditur, sic ardua scala tutius pedetentim ascenditur, sic miro modo ad veritatem, licet pigrius, tamen firmius claudicando acceditur. Sed heu mihi, quia incolatus meus prolongatus est! Quis dabit mihi pennas sicut columbae, quibus celerius volem ad veritatem, ut iam requiescam in charitate? Quae quoniam desunt, deduc me, Domine, in via tua, et ingrediar in veritate tua, et veritas liberabit me. Vae mihi quod de illa descendi. Nisi enim prius leviter, inaniter descendissem, in ascendendo tamdiu, tam graviter non laborassem. Sed quid dico, Descendi? nam fortasse rectius Cecidi dixerim. Nisi quia forte sicut nemo repente fit summus, sed gradatim quisque ascendit: sic nemo repente fit pessimus, sed paulatim descendit. Alioquin quomodo stabit illud: Impius cunctis diebus vitae suae superbit (Iob xv, 20)? Denique sunt viae, quae videntur hominibus bonae, et tamen ad malum deducunt.",
        "Gladly therefore will I glory in mine infirmity, in the shrinking of my sinew, that thy virtue — which is humility — may be made perfect in me. For thy grace is sufficient for me, when my strength has failed. I will then by thy favour put my foot firmly down, and though through its weakness I must move slowly, I will mount safely by the ladder of humility until, by keeping to the truth, I reach the broad expanse of love. Then will I sing with a gesture of thanks, the words Thou hast set my feet in a spacious place. Thus by close and careful following of the narrow way, by slow and sure ascent of the steep staircase, with steady but painful progress, I limp along until by some marvellous method, the goal is approached. But Woe is me that my sojourn is prolonged. Who will give me wings like a dove, wherewith I may fly more quickly to the truth, and so may rest in love? Since these are wanting, lead me, Lord, in thy way and I will walk in thy truth, and the truth shall set me free. Woe unto me that I ever came down thence. For had I not foolishly and madly begun this descent, I should not have had this long and laborious climb. But why do I speak of a ‘descent’ when I might more accurately call it a ‘fall’ unless indeed because, as no one comes at once to the top but all have to go up gradually, so no one becomes at once utterly bad but goes gradually down hill. Otherwise how could the saying stand, The wicked man is proud all the days of his life? There are, in fact, roads which seem good to men, which yet lead to destruction.",
        "Gladly therefore I also, Lord Jesus, will glory, if I shall be able, in my infirmity, in the contraction of my sinew, that your power, that is humility, may be perfected in me. For your grace is sufficient for me, when my power shall have failed. Firmly planting the foot of grace, and gently drawing mine, which is weak, I will ascend securely through the ladder of humility, until, clinging to the truth, I pass over to the breadth of charity. Then I will sing with thanksgiving, and I will say: You have set my feet in a spacious place. Thus the narrow way is walked more cautiously, close; thus the steep ladder is ascended more safely, step by step; thus in a wondrous manner one approaches the truth, more sluggishly indeed, yet more firmly, by limping. But alas for me, because my sojourn has been prolonged! Who will give me wings like a dove’s, by which I may fly more quickly to the truth, that I may already rest in charity? Which since they are lacking, lead me, Lord, in your way, and I will enter in your truth, and the truth will free me. Woe to me that I descended from it. For unless I had first descended lightly, emptily, I would not have laboured so long, so heavily, in ascending. But what do I say, I descended? for perhaps I would more rightly have said I fell. Except that perhaps as no one suddenly becomes highest, but each ascends by degrees: so no one suddenly becomes worst, but descends little by little. Otherwise how will that stand: The impious is proud all the days of his life? Finally there are ways that seem good to men, and yet they lead down to evil.",
      ),
      paragraph("p27", "27", [
        segment(
          "p27.1",
          "Est ergo via descensionis, sicut et ascensionis. Et via est ad bonum, et via est ad malum. Cave malam, elige bonam. Si per te non potes, ora cum Propheta, et dic: Viam iniquitatis amove a me. Quomodo? Et lege tua miserere mei, illa scilicet lege, quam dedisti delinquentibus in via, id est derelinquentibus veritatem, de quibus unus ego sum, qui vere a veritate cecidi. Sed numquid qui cadit, non adiciet ut resurgat? Propter hoc viam veritatis elegi, qua humiliatus ascendam, unde superbiendo descendi.",
          "There is then an upward as well as a downward road — a road to good and a road to evil. Avoid the evil and choose the good. If you cannot do this by yourself, pray with the prophet and in his words: Remove from me the way of iniquity, and how shall this be? He adds, Out of thy law have mercy on me. This means by the law which thou didst give to those who fainted by the way — that is to those who departed from the truth. And of these I, who have indeed fallen from the truth, am one. But does not a man who has fallen use every effort to rise again? For this reason I have chosen the way of truth, by which I may rise through humility to the place from which I fell through pride.",
          "There is therefore a way of descent, as also of ascent. And there is a way to the good, and there is a way to the evil. Beware the evil, choose the good. If through yourself you cannot, pray with the Prophet, and say: Remove the way of iniquity from me. How? And by your law have mercy on me — that law, namely, which you gave to those failing on the way, that is abandoning the truth, of whom I am one, who truly fell from the truth. But will not he who falls add that he may rise again? For this I have chosen the way of truth, by which, having been humbled, I may ascend, from where by growing proud I descended.",
        ),
        segment(
          "p27.2",
          "Ascendam, inquam, et psallam: Bonum mihi, Domine, quod humiliasti me; bonum mihi lex oris tui super millia auri et argenti. Duas tibi vias videtur David proposuisse, sed unam noveris esse; ipsam tamen a se diversam, et diversis nominibus appellatam, aut iniquitatis propter descendentes, aut veritatis propter ascendentes, quia et iidem gradus sunt ascendentium in solium et descendentium, et eadem via accedentium ad civitatem et recedentium, et unum ostium est ingredientium domum et egredientium. Per unam denique scalam ascendentes angeli et descendentes Iacob apparuerunt.",
          "I will rise, say I, and I will sing, It is good for me, Lord, that thou hast humbled me; the law of thy mouth is good to me, above thousands of gold and silver. David seems to have set before you two roads, which, however, you know to be one identical yet different — and called by different names — either that of wickedness for those who go down, or that of truth for those who go up. For you go up to a throne by the same steps by which you come down, you use the same road for approaching or withdrawing from a town, and the same door for entering or leaving a house. In like manner the angels appeared to Jacob as ascending and descending on the same ladder.",
          "I will ascend, I say, and I will sing: It is good for me, Lord, that you have humbled me; good for me is the law of your mouth above thousands of gold and silver. David seems to have proposed two ways to you, but you should know them to be one; yet diverse from itself, and called by diverse names, either of iniquity because of those descending, or of truth because of those ascending, because the same degrees are of those ascending onto a throne and of those descending, and the same way of those approaching a city and of those withdrawing, and one door is of those entering a house and of those going out. Finally through one ladder the angels appeared to Jacob ascending and descending.",
        ),
        segment(
          "p27.3",
          "Quo spectant haec? Vt videlicet si ad veritatem redire cupis, non necesse sit viam quaerere novam quam non nosti, sed notam qua descendisti: quatenus reciprocis gressibus tua ipse vestigia sequens, per eosdem gradus humiliatus ascendas, per quos superbiendo descenderas, ita ut qui duodecimus superbiae fuit descendenti, primus humilitatis sit ascendenti; undecimus, inveniatur secundus; decimus, tertius; nonus, quartus; octavus, quintus; septimus, sextus; sextus, septimus; quintus, octavus; quartus, nonus; tertius, decimus; secundus, undecimus; primus, duodecimus. Quibus superbiae gradibus in te inventis, immo recognitis, iam non laboras in quaerendo viam humilitatis.",
          "What do these comparisons suggest? Surely that if you wish to return to the truth, you need not look for a new and unknown road, but for the one by which you know that you came down, so that you may follow your own footsteps, and may humbly rise through the same degrees through which you fell in your pride. That which was the twelfth degree of pride in your fall will be the first degree of humility in your ascent; the eleventh will correspond to the second, the tenth to the third, the ninth to the fourth, the eighth to the fifth, the seventh to the sixth, the sixth to the seventh, the fifth to the eighth, the fourth to the ninth, the third to the tenth, the second to the eleventh and the first to the twelfth. And when you have discovered and really recognized these degrees of pride in yourself, you will have no difficulty in looking for the path of humility.",
          "Toward what do these look? Namely that if you desire to return to the truth, it may not be necessary to seek a new way which you do not know, but the known one by which you descended: so that by reciprocal steps, yourself following your footprints, you may ascend humbled through the same degrees through which you had descended by growing proud, so that he who was twelfth of pride for the one descending may be first of humility for the one ascending; the eleventh may be found the second; the tenth, the third; the ninth, the fourth; the eighth, the fifth; the seventh, the sixth; the sixth, the seventh; the fifth, the eighth; the fourth, the ninth; the third, the tenth; the second, the eleventh; the first, the twelfth. Which degrees of pride having been found in you — nay rather recognized — you no longer labour in seeking the way of humility.",
          [
            {
              kind: "syntax",
              title: "the inverted ladder",
              body: "Bernard’s period is one sentence of paired ordinals. Mills breaks it into correspondence-clauses. The close line keeps the inversion as a single climb back down the same steps.",
            },
          ],
        ),
      ]),
    ],
  },
];
